//! MPI callback function pointer type aliases.
//!
//! Auto-generated by gen_rust.py. Do not edit manually.
//!
//! These use `Option<fn(...)>` to match bindgen's convention for C function
//! pointers, which are nullable by default.

use std::os::raw::{c_int, c_void};

use crate::types::*;

pub type MPI_User_function = Option<
    unsafe extern "C" fn(
        invec: *mut c_void,
        inoutvec: *mut c_void,
        len: *mut c_int,
        datatype: *mut MPI_Datatype,
    ),
>;

pub type MPI_Comm_copy_attr_function = Option<
    unsafe extern "C" fn(
        comm: MPI_Comm,
        comm_keyval: c_int,
        extra_state: *mut c_void,
        attribute_val_in: *mut c_void,
        attribute_val_out: *mut c_void,
        flag: *mut c_int,
    ) -> c_int,
>;

pub type MPI_Comm_delete_attr_function = Option<
    unsafe extern "C" fn(
        comm: MPI_Comm,
        comm_keyval: c_int,
        attribute_val: *mut c_void,
        extra_state: *mut c_void,
    ) -> c_int,
>;

pub type MPI_Comm_errhandler_function =
    Option<unsafe extern "C" fn(comm: *mut MPI_Comm, error_code: *mut c_int)>;

pub type MPI_Win_copy_attr_function = Option<
    unsafe extern "C" fn(
        win: MPI_Win,
        win_keyval: c_int,
        extra_state: *mut c_void,
        attribute_val_in: *mut c_void,
        attribute_val_out: *mut c_void,
        flag: *mut c_int,
    ) -> c_int,
>;

pub type MPI_Win_delete_attr_function = Option<
    unsafe extern "C" fn(
        win: MPI_Win,
        win_keyval: c_int,
        attribute_val: *mut c_void,
        extra_state: *mut c_void,
    ) -> c_int,
>;

pub type MPI_Win_errhandler_function =
    Option<unsafe extern "C" fn(win: *mut MPI_Win, error_code: *mut c_int)>;

pub type MPI_Type_copy_attr_function = Option<
    unsafe extern "C" fn(
        oldtype: MPI_Datatype,
        type_keyval: c_int,
        extra_state: *mut c_void,
        attribute_val_in: *mut c_void,
        attribute_val_out: *mut c_void,
        flag: *mut c_int,
    ) -> c_int,
>;

pub type MPI_Type_delete_attr_function = Option<
    unsafe extern "C" fn(
        datatype: MPI_Datatype,
        type_keyval: c_int,
        attribute_val: *mut c_void,
        extra_state: *mut c_void,
    ) -> c_int,
>;

pub type MPI_Copy_function = Option<
    unsafe extern "C" fn(
        comm: MPI_Comm,
        keyval: c_int,
        extra_state: *mut c_void,
        attribute_val_in: *mut c_void,
        attribute_val_out: *mut c_void,
        flag: *mut c_int,
    ) -> c_int,
>;

pub type MPI_Delete_function = Option<
    unsafe extern "C" fn(
        comm: MPI_Comm,
        keyval: c_int,
        attribute_val: *mut c_void,
        extra_state: *mut c_void,
    ) -> c_int,
>;

pub type MPI_File_errhandler_function =
    Option<unsafe extern "C" fn(file: *mut MPI_File, error_code: *mut c_int)>;

pub type MPI_Grequest_query_function =
    Option<unsafe extern "C" fn(extra_state: *mut c_void, status: *mut MPI_Status) -> c_int>;

pub type MPI_Grequest_free_function =
    Option<unsafe extern "C" fn(extra_state: *mut c_void) -> c_int>;

pub type MPI_Grequest_cancel_function =
    Option<unsafe extern "C" fn(extra_state: *mut c_void, complete: c_int) -> c_int>;

pub type MPI_Datarep_conversion_function = Option<
    unsafe extern "C" fn(
        userbuf: *mut c_void,
        datatype: MPI_Datatype,
        count: c_int,
        filebuf: *mut c_void,
        position: MPI_Offset,
        extra_state: *mut c_void,
    ) -> c_int,
>;

pub type MPI_Datarep_extent_function = Option<
    unsafe extern "C" fn(
        datatype: MPI_Datatype,
        extent: *mut MPI_Aint,
        extra_state: *mut c_void,
    ) -> c_int,
>;
