//! MPI constant accessors via dynamic loading.
//!
//! Auto-generated by gen_rust.py. Do not edit manually.

use std::os::raw::{c_char, c_double, c_int, c_void};
use std::sync::OnceLock;

use crate::callback_types::*;
use crate::types::*;
use crate::loader;

struct MpiConstants {
    mpi_any_source: c_int,
    mpi_any_tag: c_int,
    mpi_proc_null: c_int,
    mpi_root: c_int,
    mpi_cart: c_int,
    mpi_dist_graph: c_int,
    mpi_graph: c_int,
    mpi_congruent: c_int,
    mpi_ident: c_int,
    mpi_similar: c_int,
    mpi_unequal: c_int,
    mpi_bsend_overhead: c_int,
    mpi_keyval_invalid: c_int,
    mpi_undefined: c_int,
    mpi_appnum: c_int,
    mpi_host: c_int,
    mpi_io: c_int,
    mpi_lastusedcode: c_int,
    mpi_tag_ub: c_int,
    mpi_universe_size: c_int,
    mpi_win_base: c_int,
    mpi_win_create_flavor: c_int,
    mpi_win_disp_unit: c_int,
    mpi_win_model: c_int,
    mpi_win_size: c_int,
    mpi_wtime_is_global: c_int,
    mpi_combiner_contiguous: c_int,
    mpi_combiner_darray: c_int,
    mpi_combiner_dup: c_int,
    mpi_combiner_f90_complex: c_int,
    mpi_combiner_f90_integer: c_int,
    mpi_combiner_f90_real: c_int,
    mpi_combiner_hindexed: c_int,
    mpi_combiner_hindexed_block: c_int,
    mpi_combiner_hvector: c_int,
    mpi_combiner_indexed: c_int,
    mpi_combiner_indexed_block: c_int,
    mpi_combiner_named: c_int,
    mpi_combiner_resized: c_int,
    mpi_combiner_struct: c_int,
    mpi_combiner_subarray: c_int,
    mpi_combiner_vector: c_int,
    mpi_comm_type_shared: c_int,
    mpi_distribute_block: c_int,
    mpi_distribute_cyclic: c_int,
    mpi_distribute_dflt_darg: c_int,
    mpi_distribute_none: c_int,
    mpi_err_access: c_int,
    mpi_err_amode: c_int,
    mpi_err_arg: c_int,
    mpi_err_assert: c_int,
    mpi_err_bad_file: c_int,
    mpi_err_base: c_int,
    mpi_err_buffer: c_int,
    mpi_err_comm: c_int,
    mpi_err_conversion: c_int,
    mpi_err_count: c_int,
    mpi_err_dims: c_int,
    mpi_err_disp: c_int,
    mpi_err_dup_datarep: c_int,
    mpi_err_file: c_int,
    mpi_err_file_exists: c_int,
    mpi_err_file_in_use: c_int,
    mpi_err_group: c_int,
    mpi_err_info: c_int,
    mpi_err_info_key: c_int,
    mpi_err_info_nokey: c_int,
    mpi_err_info_value: c_int,
    mpi_err_intern: c_int,
    mpi_err_in_status: c_int,
    mpi_err_io: c_int,
    mpi_err_keyval: c_int,
    mpi_err_lastcode: c_int,
    mpi_err_locktype: c_int,
    mpi_err_name: c_int,
    mpi_err_not_same: c_int,
    mpi_err_no_mem: c_int,
    mpi_err_no_space: c_int,
    mpi_err_no_such_file: c_int,
    mpi_err_op: c_int,
    mpi_err_other: c_int,
    mpi_err_pending: c_int,
    mpi_err_port: c_int,
    mpi_err_quota: c_int,
    mpi_err_rank: c_int,
    mpi_err_read_only: c_int,
    mpi_err_request: c_int,
    mpi_err_rma_attach: c_int,
    mpi_err_rma_conflict: c_int,
    mpi_err_rma_flavor: c_int,
    mpi_err_rma_range: c_int,
    mpi_err_rma_shared: c_int,
    mpi_err_rma_sync: c_int,
    mpi_err_root: c_int,
    mpi_err_service: c_int,
    mpi_err_size: c_int,
    mpi_err_spawn: c_int,
    mpi_err_tag: c_int,
    mpi_err_topology: c_int,
    mpi_err_truncate: c_int,
    mpi_err_type: c_int,
    mpi_err_unknown: c_int,
    mpi_err_unsupported_datarep: c_int,
    mpi_err_unsupported_operation: c_int,
    mpi_err_win: c_int,
    mpi_success: c_int,
    mpi_lock_exclusive: c_int,
    mpi_lock_shared: c_int,
    mpi_mode_append: c_int,
    mpi_mode_create: c_int,
    mpi_mode_delete_on_close: c_int,
    mpi_mode_excl: c_int,
    mpi_mode_nocheck: c_int,
    mpi_mode_noprecede: c_int,
    mpi_mode_noput: c_int,
    mpi_mode_nostore: c_int,
    mpi_mode_nosucceed: c_int,
    mpi_mode_rdonly: c_int,
    mpi_mode_rdwr: c_int,
    mpi_mode_sequential: c_int,
    mpi_mode_unique_open: c_int,
    mpi_mode_wronly: c_int,
    mpi_order_c: c_int,
    mpi_order_fortran: c_int,
    mpi_seek_cur: c_int,
    mpi_seek_end: c_int,
    mpi_seek_set: c_int,
    mpi_thread_funneled: c_int,
    mpi_thread_multiple: c_int,
    mpi_thread_serialized: c_int,
    mpi_thread_single: c_int,
    mpi_typeclass_complex: c_int,
    mpi_typeclass_integer: c_int,
    mpi_typeclass_real: c_int,
    mpi_win_flavor_allocate: c_int,
    mpi_win_flavor_create: c_int,
    mpi_win_flavor_dynamic: c_int,
    mpi_win_flavor_shared: c_int,
    mpi_win_separate: c_int,
    mpi_win_unified: c_int,
    mpi_argv_null: *mut *mut c_char,
    mpi_argvs_null: *mut *mut *mut c_char,
    mpi_errcodes_ignore: *mut c_int,
    mpi_unweighted: *mut c_int,
    mpi_weights_empty: *mut c_int,
    mpi_bottom: *mut c_void,
    mpi_in_place: *mut c_void,
    mpi_comm_null: MPI_Comm,
    mpi_comm_self: MPI_Comm,
    mpi_comm_world: MPI_Comm,
    mpi_comm_dup_fn: MPI_Comm_copy_attr_function,
    mpi_comm_null_copy_fn: MPI_Comm_copy_attr_function,
    mpi_comm_null_delete_fn: MPI_Comm_delete_attr_function,
    mpi_dup_fn: MPI_Copy_function,
    mpi_null_copy_fn: MPI_Copy_function,
    mpi_conversion_fn_null: MPI_Datarep_conversion_function,
    mpi_2double_precision: MPI_Datatype,
    mpi_2int: MPI_Datatype,
    mpi_2integer: MPI_Datatype,
    mpi_2real: MPI_Datatype,
    mpi_aint: MPI_Datatype,
    mpi_byte: MPI_Datatype,
    mpi_char: MPI_Datatype,
    mpi_character: MPI_Datatype,
    mpi_complex: MPI_Datatype,
    mpi_complex16: MPI_Datatype,
    mpi_complex32: MPI_Datatype,
    mpi_complex8: MPI_Datatype,
    mpi_count: MPI_Datatype,
    mpi_cxx_bool: MPI_Datatype,
    mpi_cxx_double_complex: MPI_Datatype,
    mpi_cxx_float_complex: MPI_Datatype,
    mpi_cxx_long_double_complex: MPI_Datatype,
    mpi_c_bool: MPI_Datatype,
    mpi_c_complex: MPI_Datatype,
    mpi_c_double_complex: MPI_Datatype,
    mpi_c_float_complex: MPI_Datatype,
    mpi_c_long_double_complex: MPI_Datatype,
    mpi_datatype_null: MPI_Datatype,
    mpi_double: MPI_Datatype,
    mpi_double_complex: MPI_Datatype,
    mpi_double_int: MPI_Datatype,
    mpi_double_precision: MPI_Datatype,
    mpi_float: MPI_Datatype,
    mpi_float_int: MPI_Datatype,
    mpi_int: MPI_Datatype,
    mpi_int16_t: MPI_Datatype,
    mpi_int32_t: MPI_Datatype,
    mpi_int64_t: MPI_Datatype,
    mpi_int8_t: MPI_Datatype,
    mpi_integer: MPI_Datatype,
    mpi_integer1: MPI_Datatype,
    mpi_integer2: MPI_Datatype,
    mpi_integer4: MPI_Datatype,
    mpi_integer8: MPI_Datatype,
    mpi_logical: MPI_Datatype,
    mpi_long: MPI_Datatype,
    mpi_long_double: MPI_Datatype,
    mpi_long_double_int: MPI_Datatype,
    mpi_long_int: MPI_Datatype,
    mpi_long_long: MPI_Datatype,
    mpi_long_long_int: MPI_Datatype,
    mpi_offset: MPI_Datatype,
    mpi_packed: MPI_Datatype,
    mpi_real: MPI_Datatype,
    mpi_real16: MPI_Datatype,
    mpi_real4: MPI_Datatype,
    mpi_real8: MPI_Datatype,
    mpi_short: MPI_Datatype,
    mpi_short_int: MPI_Datatype,
    mpi_signed_char: MPI_Datatype,
    mpi_uint16_t: MPI_Datatype,
    mpi_uint32_t: MPI_Datatype,
    mpi_uint64_t: MPI_Datatype,
    mpi_uint8_t: MPI_Datatype,
    mpi_unsigned: MPI_Datatype,
    mpi_unsigned_char: MPI_Datatype,
    mpi_unsigned_long: MPI_Datatype,
    mpi_unsigned_long_long: MPI_Datatype,
    mpi_unsigned_short: MPI_Datatype,
    mpi_wchar: MPI_Datatype,
    mpi_null_delete_fn: MPI_Delete_function,
    mpi_errhandler_null: MPI_Errhandler,
    mpi_errors_are_fatal: MPI_Errhandler,
    mpi_errors_return: MPI_Errhandler,
    mpi_file_null: MPI_File,
    mpi_f_status_ignore: *mut MPI_Fint,
    mpi_f_statuses_ignore: *mut MPI_Fint,
    mpi_group_empty: MPI_Group,
    mpi_group_null: MPI_Group,
    mpi_info_env: MPI_Info,
    mpi_info_null: MPI_Info,
    mpi_message_no_proc: MPI_Message,
    mpi_message_null: MPI_Message,
    mpi_displacement_current: MPI_Offset,
    mpi_band: MPI_Op,
    mpi_bor: MPI_Op,
    mpi_bxor: MPI_Op,
    mpi_land: MPI_Op,
    mpi_lor: MPI_Op,
    mpi_lxor: MPI_Op,
    mpi_max: MPI_Op,
    mpi_maxloc: MPI_Op,
    mpi_min: MPI_Op,
    mpi_minloc: MPI_Op,
    mpi_no_op: MPI_Op,
    mpi_op_null: MPI_Op,
    mpi_prod: MPI_Op,
    mpi_replace: MPI_Op,
    mpi_sum: MPI_Op,
    mpi_request_null: MPI_Request,
    mpi_status_ignore: *mut MPI_Status,
    mpi_statuses_ignore: *mut MPI_Status,
    mpi_type_dup_fn: MPI_Type_copy_attr_function,
    mpi_type_null_copy_fn: MPI_Type_copy_attr_function,
    mpi_type_null_delete_fn: MPI_Type_delete_attr_function,
    mpi_win_null: MPI_Win,
    mpi_win_dup_fn: MPI_Win_copy_attr_function,
    mpi_win_null_copy_fn: MPI_Win_copy_attr_function,
    mpi_win_null_delete_fn: MPI_Win_delete_attr_function,
}

// SAFETY: MPI constants are initialized once and then read-only.
// The raw pointers (e.g. MPI_STATUS_IGNORE) are global MPI constants
// that remain valid for the lifetime of the program.
unsafe impl Send for MpiConstants {}
unsafe impl Sync for MpiConstants {}

static CONSTANTS: OnceLock<MpiConstants> = OnceLock::new();

fn get_constants() -> &'static MpiConstants {
    CONSTANTS.get_or_init(|| {
        let lib = loader::library();
        unsafe {
            MpiConstants {
                mpi_any_source: *lib.get::<c_int>(b"MPIABI_ANY_SOURCE\0").expect("symbol MPIABI_ANY_SOURCE"),
                mpi_any_tag: *lib.get::<c_int>(b"MPIABI_ANY_TAG\0").expect("symbol MPIABI_ANY_TAG"),
                mpi_proc_null: *lib.get::<c_int>(b"MPIABI_PROC_NULL\0").expect("symbol MPIABI_PROC_NULL"),
                mpi_root: *lib.get::<c_int>(b"MPIABI_ROOT\0").expect("symbol MPIABI_ROOT"),
                mpi_cart: *lib.get::<c_int>(b"MPIABI_CART\0").expect("symbol MPIABI_CART"),
                mpi_dist_graph: *lib.get::<c_int>(b"MPIABI_DIST_GRAPH\0").expect("symbol MPIABI_DIST_GRAPH"),
                mpi_graph: *lib.get::<c_int>(b"MPIABI_GRAPH\0").expect("symbol MPIABI_GRAPH"),
                mpi_congruent: *lib.get::<c_int>(b"MPIABI_CONGRUENT\0").expect("symbol MPIABI_CONGRUENT"),
                mpi_ident: *lib.get::<c_int>(b"MPIABI_IDENT\0").expect("symbol MPIABI_IDENT"),
                mpi_similar: *lib.get::<c_int>(b"MPIABI_SIMILAR\0").expect("symbol MPIABI_SIMILAR"),
                mpi_unequal: *lib.get::<c_int>(b"MPIABI_UNEQUAL\0").expect("symbol MPIABI_UNEQUAL"),
                mpi_bsend_overhead: *lib.get::<c_int>(b"MPIABI_BSEND_OVERHEAD\0").expect("symbol MPIABI_BSEND_OVERHEAD"),
                mpi_keyval_invalid: *lib.get::<c_int>(b"MPIABI_KEYVAL_INVALID\0").expect("symbol MPIABI_KEYVAL_INVALID"),
                mpi_undefined: *lib.get::<c_int>(b"MPIABI_UNDEFINED\0").expect("symbol MPIABI_UNDEFINED"),
                mpi_appnum: *lib.get::<c_int>(b"MPIABI_APPNUM\0").expect("symbol MPIABI_APPNUM"),
                mpi_host: *lib.get::<c_int>(b"MPIABI_HOST\0").expect("symbol MPIABI_HOST"),
                mpi_io: *lib.get::<c_int>(b"MPIABI_IO\0").expect("symbol MPIABI_IO"),
                mpi_lastusedcode: *lib.get::<c_int>(b"MPIABI_LASTUSEDCODE\0").expect("symbol MPIABI_LASTUSEDCODE"),
                mpi_tag_ub: *lib.get::<c_int>(b"MPIABI_TAG_UB\0").expect("symbol MPIABI_TAG_UB"),
                mpi_universe_size: *lib.get::<c_int>(b"MPIABI_UNIVERSE_SIZE\0").expect("symbol MPIABI_UNIVERSE_SIZE"),
                mpi_win_base: *lib.get::<c_int>(b"MPIABI_WIN_BASE\0").expect("symbol MPIABI_WIN_BASE"),
                mpi_win_create_flavor: *lib.get::<c_int>(b"MPIABI_WIN_CREATE_FLAVOR\0").expect("symbol MPIABI_WIN_CREATE_FLAVOR"),
                mpi_win_disp_unit: *lib.get::<c_int>(b"MPIABI_WIN_DISP_UNIT\0").expect("symbol MPIABI_WIN_DISP_UNIT"),
                mpi_win_model: *lib.get::<c_int>(b"MPIABI_WIN_MODEL\0").expect("symbol MPIABI_WIN_MODEL"),
                mpi_win_size: *lib.get::<c_int>(b"MPIABI_WIN_SIZE\0").expect("symbol MPIABI_WIN_SIZE"),
                mpi_wtime_is_global: *lib.get::<c_int>(b"MPIABI_WTIME_IS_GLOBAL\0").expect("symbol MPIABI_WTIME_IS_GLOBAL"),
                mpi_combiner_contiguous: *lib.get::<c_int>(b"MPIABI_COMBINER_CONTIGUOUS\0").expect("symbol MPIABI_COMBINER_CONTIGUOUS"),
                mpi_combiner_darray: *lib.get::<c_int>(b"MPIABI_COMBINER_DARRAY\0").expect("symbol MPIABI_COMBINER_DARRAY"),
                mpi_combiner_dup: *lib.get::<c_int>(b"MPIABI_COMBINER_DUP\0").expect("symbol MPIABI_COMBINER_DUP"),
                mpi_combiner_f90_complex: *lib.get::<c_int>(b"MPIABI_COMBINER_F90_COMPLEX\0").expect("symbol MPIABI_COMBINER_F90_COMPLEX"),
                mpi_combiner_f90_integer: *lib.get::<c_int>(b"MPIABI_COMBINER_F90_INTEGER\0").expect("symbol MPIABI_COMBINER_F90_INTEGER"),
                mpi_combiner_f90_real: *lib.get::<c_int>(b"MPIABI_COMBINER_F90_REAL\0").expect("symbol MPIABI_COMBINER_F90_REAL"),
                mpi_combiner_hindexed: *lib.get::<c_int>(b"MPIABI_COMBINER_HINDEXED\0").expect("symbol MPIABI_COMBINER_HINDEXED"),
                mpi_combiner_hindexed_block: *lib.get::<c_int>(b"MPIABI_COMBINER_HINDEXED_BLOCK\0").expect("symbol MPIABI_COMBINER_HINDEXED_BLOCK"),
                mpi_combiner_hvector: *lib.get::<c_int>(b"MPIABI_COMBINER_HVECTOR\0").expect("symbol MPIABI_COMBINER_HVECTOR"),
                mpi_combiner_indexed: *lib.get::<c_int>(b"MPIABI_COMBINER_INDEXED\0").expect("symbol MPIABI_COMBINER_INDEXED"),
                mpi_combiner_indexed_block: *lib.get::<c_int>(b"MPIABI_COMBINER_INDEXED_BLOCK\0").expect("symbol MPIABI_COMBINER_INDEXED_BLOCK"),
                mpi_combiner_named: *lib.get::<c_int>(b"MPIABI_COMBINER_NAMED\0").expect("symbol MPIABI_COMBINER_NAMED"),
                mpi_combiner_resized: *lib.get::<c_int>(b"MPIABI_COMBINER_RESIZED\0").expect("symbol MPIABI_COMBINER_RESIZED"),
                mpi_combiner_struct: *lib.get::<c_int>(b"MPIABI_COMBINER_STRUCT\0").expect("symbol MPIABI_COMBINER_STRUCT"),
                mpi_combiner_subarray: *lib.get::<c_int>(b"MPIABI_COMBINER_SUBARRAY\0").expect("symbol MPIABI_COMBINER_SUBARRAY"),
                mpi_combiner_vector: *lib.get::<c_int>(b"MPIABI_COMBINER_VECTOR\0").expect("symbol MPIABI_COMBINER_VECTOR"),
                mpi_comm_type_shared: *lib.get::<c_int>(b"MPIABI_COMM_TYPE_SHARED\0").expect("symbol MPIABI_COMM_TYPE_SHARED"),
                mpi_distribute_block: *lib.get::<c_int>(b"MPIABI_DISTRIBUTE_BLOCK\0").expect("symbol MPIABI_DISTRIBUTE_BLOCK"),
                mpi_distribute_cyclic: *lib.get::<c_int>(b"MPIABI_DISTRIBUTE_CYCLIC\0").expect("symbol MPIABI_DISTRIBUTE_CYCLIC"),
                mpi_distribute_dflt_darg: *lib.get::<c_int>(b"MPIABI_DISTRIBUTE_DFLT_DARG\0").expect("symbol MPIABI_DISTRIBUTE_DFLT_DARG"),
                mpi_distribute_none: *lib.get::<c_int>(b"MPIABI_DISTRIBUTE_NONE\0").expect("symbol MPIABI_DISTRIBUTE_NONE"),
                mpi_err_access: *lib.get::<c_int>(b"MPIABI_ERR_ACCESS\0").expect("symbol MPIABI_ERR_ACCESS"),
                mpi_err_amode: *lib.get::<c_int>(b"MPIABI_ERR_AMODE\0").expect("symbol MPIABI_ERR_AMODE"),
                mpi_err_arg: *lib.get::<c_int>(b"MPIABI_ERR_ARG\0").expect("symbol MPIABI_ERR_ARG"),
                mpi_err_assert: *lib.get::<c_int>(b"MPIABI_ERR_ASSERT\0").expect("symbol MPIABI_ERR_ASSERT"),
                mpi_err_bad_file: *lib.get::<c_int>(b"MPIABI_ERR_BAD_FILE\0").expect("symbol MPIABI_ERR_BAD_FILE"),
                mpi_err_base: *lib.get::<c_int>(b"MPIABI_ERR_BASE\0").expect("symbol MPIABI_ERR_BASE"),
                mpi_err_buffer: *lib.get::<c_int>(b"MPIABI_ERR_BUFFER\0").expect("symbol MPIABI_ERR_BUFFER"),
                mpi_err_comm: *lib.get::<c_int>(b"MPIABI_ERR_COMM\0").expect("symbol MPIABI_ERR_COMM"),
                mpi_err_conversion: *lib.get::<c_int>(b"MPIABI_ERR_CONVERSION\0").expect("symbol MPIABI_ERR_CONVERSION"),
                mpi_err_count: *lib.get::<c_int>(b"MPIABI_ERR_COUNT\0").expect("symbol MPIABI_ERR_COUNT"),
                mpi_err_dims: *lib.get::<c_int>(b"MPIABI_ERR_DIMS\0").expect("symbol MPIABI_ERR_DIMS"),
                mpi_err_disp: *lib.get::<c_int>(b"MPIABI_ERR_DISP\0").expect("symbol MPIABI_ERR_DISP"),
                mpi_err_dup_datarep: *lib.get::<c_int>(b"MPIABI_ERR_DUP_DATAREP\0").expect("symbol MPIABI_ERR_DUP_DATAREP"),
                mpi_err_file: *lib.get::<c_int>(b"MPIABI_ERR_FILE\0").expect("symbol MPIABI_ERR_FILE"),
                mpi_err_file_exists: *lib.get::<c_int>(b"MPIABI_ERR_FILE_EXISTS\0").expect("symbol MPIABI_ERR_FILE_EXISTS"),
                mpi_err_file_in_use: *lib.get::<c_int>(b"MPIABI_ERR_FILE_IN_USE\0").expect("symbol MPIABI_ERR_FILE_IN_USE"),
                mpi_err_group: *lib.get::<c_int>(b"MPIABI_ERR_GROUP\0").expect("symbol MPIABI_ERR_GROUP"),
                mpi_err_info: *lib.get::<c_int>(b"MPIABI_ERR_INFO\0").expect("symbol MPIABI_ERR_INFO"),
                mpi_err_info_key: *lib.get::<c_int>(b"MPIABI_ERR_INFO_KEY\0").expect("symbol MPIABI_ERR_INFO_KEY"),
                mpi_err_info_nokey: *lib.get::<c_int>(b"MPIABI_ERR_INFO_NOKEY\0").expect("symbol MPIABI_ERR_INFO_NOKEY"),
                mpi_err_info_value: *lib.get::<c_int>(b"MPIABI_ERR_INFO_VALUE\0").expect("symbol MPIABI_ERR_INFO_VALUE"),
                mpi_err_intern: *lib.get::<c_int>(b"MPIABI_ERR_INTERN\0").expect("symbol MPIABI_ERR_INTERN"),
                mpi_err_in_status: *lib.get::<c_int>(b"MPIABI_ERR_IN_STATUS\0").expect("symbol MPIABI_ERR_IN_STATUS"),
                mpi_err_io: *lib.get::<c_int>(b"MPIABI_ERR_IO\0").expect("symbol MPIABI_ERR_IO"),
                mpi_err_keyval: *lib.get::<c_int>(b"MPIABI_ERR_KEYVAL\0").expect("symbol MPIABI_ERR_KEYVAL"),
                mpi_err_lastcode: *lib.get::<c_int>(b"MPIABI_ERR_LASTCODE\0").expect("symbol MPIABI_ERR_LASTCODE"),
                mpi_err_locktype: *lib.get::<c_int>(b"MPIABI_ERR_LOCKTYPE\0").expect("symbol MPIABI_ERR_LOCKTYPE"),
                mpi_err_name: *lib.get::<c_int>(b"MPIABI_ERR_NAME\0").expect("symbol MPIABI_ERR_NAME"),
                mpi_err_not_same: *lib.get::<c_int>(b"MPIABI_ERR_NOT_SAME\0").expect("symbol MPIABI_ERR_NOT_SAME"),
                mpi_err_no_mem: *lib.get::<c_int>(b"MPIABI_ERR_NO_MEM\0").expect("symbol MPIABI_ERR_NO_MEM"),
                mpi_err_no_space: *lib.get::<c_int>(b"MPIABI_ERR_NO_SPACE\0").expect("symbol MPIABI_ERR_NO_SPACE"),
                mpi_err_no_such_file: *lib.get::<c_int>(b"MPIABI_ERR_NO_SUCH_FILE\0").expect("symbol MPIABI_ERR_NO_SUCH_FILE"),
                mpi_err_op: *lib.get::<c_int>(b"MPIABI_ERR_OP\0").expect("symbol MPIABI_ERR_OP"),
                mpi_err_other: *lib.get::<c_int>(b"MPIABI_ERR_OTHER\0").expect("symbol MPIABI_ERR_OTHER"),
                mpi_err_pending: *lib.get::<c_int>(b"MPIABI_ERR_PENDING\0").expect("symbol MPIABI_ERR_PENDING"),
                mpi_err_port: *lib.get::<c_int>(b"MPIABI_ERR_PORT\0").expect("symbol MPIABI_ERR_PORT"),
                mpi_err_quota: *lib.get::<c_int>(b"MPIABI_ERR_QUOTA\0").expect("symbol MPIABI_ERR_QUOTA"),
                mpi_err_rank: *lib.get::<c_int>(b"MPIABI_ERR_RANK\0").expect("symbol MPIABI_ERR_RANK"),
                mpi_err_read_only: *lib.get::<c_int>(b"MPIABI_ERR_READ_ONLY\0").expect("symbol MPIABI_ERR_READ_ONLY"),
                mpi_err_request: *lib.get::<c_int>(b"MPIABI_ERR_REQUEST\0").expect("symbol MPIABI_ERR_REQUEST"),
                mpi_err_rma_attach: *lib.get::<c_int>(b"MPIABI_ERR_RMA_ATTACH\0").expect("symbol MPIABI_ERR_RMA_ATTACH"),
                mpi_err_rma_conflict: *lib.get::<c_int>(b"MPIABI_ERR_RMA_CONFLICT\0").expect("symbol MPIABI_ERR_RMA_CONFLICT"),
                mpi_err_rma_flavor: *lib.get::<c_int>(b"MPIABI_ERR_RMA_FLAVOR\0").expect("symbol MPIABI_ERR_RMA_FLAVOR"),
                mpi_err_rma_range: *lib.get::<c_int>(b"MPIABI_ERR_RMA_RANGE\0").expect("symbol MPIABI_ERR_RMA_RANGE"),
                mpi_err_rma_shared: *lib.get::<c_int>(b"MPIABI_ERR_RMA_SHARED\0").expect("symbol MPIABI_ERR_RMA_SHARED"),
                mpi_err_rma_sync: *lib.get::<c_int>(b"MPIABI_ERR_RMA_SYNC\0").expect("symbol MPIABI_ERR_RMA_SYNC"),
                mpi_err_root: *lib.get::<c_int>(b"MPIABI_ERR_ROOT\0").expect("symbol MPIABI_ERR_ROOT"),
                mpi_err_service: *lib.get::<c_int>(b"MPIABI_ERR_SERVICE\0").expect("symbol MPIABI_ERR_SERVICE"),
                mpi_err_size: *lib.get::<c_int>(b"MPIABI_ERR_SIZE\0").expect("symbol MPIABI_ERR_SIZE"),
                mpi_err_spawn: *lib.get::<c_int>(b"MPIABI_ERR_SPAWN\0").expect("symbol MPIABI_ERR_SPAWN"),
                mpi_err_tag: *lib.get::<c_int>(b"MPIABI_ERR_TAG\0").expect("symbol MPIABI_ERR_TAG"),
                mpi_err_topology: *lib.get::<c_int>(b"MPIABI_ERR_TOPOLOGY\0").expect("symbol MPIABI_ERR_TOPOLOGY"),
                mpi_err_truncate: *lib.get::<c_int>(b"MPIABI_ERR_TRUNCATE\0").expect("symbol MPIABI_ERR_TRUNCATE"),
                mpi_err_type: *lib.get::<c_int>(b"MPIABI_ERR_TYPE\0").expect("symbol MPIABI_ERR_TYPE"),
                mpi_err_unknown: *lib.get::<c_int>(b"MPIABI_ERR_UNKNOWN\0").expect("symbol MPIABI_ERR_UNKNOWN"),
                mpi_err_unsupported_datarep: *lib.get::<c_int>(b"MPIABI_ERR_UNSUPPORTED_DATAREP\0").expect("symbol MPIABI_ERR_UNSUPPORTED_DATAREP"),
                mpi_err_unsupported_operation: *lib.get::<c_int>(b"MPIABI_ERR_UNSUPPORTED_OPERATION\0").expect("symbol MPIABI_ERR_UNSUPPORTED_OPERATION"),
                mpi_err_win: *lib.get::<c_int>(b"MPIABI_ERR_WIN\0").expect("symbol MPIABI_ERR_WIN"),
                mpi_success: *lib.get::<c_int>(b"MPIABI_SUCCESS\0").expect("symbol MPIABI_SUCCESS"),
                mpi_lock_exclusive: *lib.get::<c_int>(b"MPIABI_LOCK_EXCLUSIVE\0").expect("symbol MPIABI_LOCK_EXCLUSIVE"),
                mpi_lock_shared: *lib.get::<c_int>(b"MPIABI_LOCK_SHARED\0").expect("symbol MPIABI_LOCK_SHARED"),
                mpi_mode_append: *lib.get::<c_int>(b"MPIABI_MODE_APPEND\0").expect("symbol MPIABI_MODE_APPEND"),
                mpi_mode_create: *lib.get::<c_int>(b"MPIABI_MODE_CREATE\0").expect("symbol MPIABI_MODE_CREATE"),
                mpi_mode_delete_on_close: *lib.get::<c_int>(b"MPIABI_MODE_DELETE_ON_CLOSE\0").expect("symbol MPIABI_MODE_DELETE_ON_CLOSE"),
                mpi_mode_excl: *lib.get::<c_int>(b"MPIABI_MODE_EXCL\0").expect("symbol MPIABI_MODE_EXCL"),
                mpi_mode_nocheck: *lib.get::<c_int>(b"MPIABI_MODE_NOCHECK\0").expect("symbol MPIABI_MODE_NOCHECK"),
                mpi_mode_noprecede: *lib.get::<c_int>(b"MPIABI_MODE_NOPRECEDE\0").expect("symbol MPIABI_MODE_NOPRECEDE"),
                mpi_mode_noput: *lib.get::<c_int>(b"MPIABI_MODE_NOPUT\0").expect("symbol MPIABI_MODE_NOPUT"),
                mpi_mode_nostore: *lib.get::<c_int>(b"MPIABI_MODE_NOSTORE\0").expect("symbol MPIABI_MODE_NOSTORE"),
                mpi_mode_nosucceed: *lib.get::<c_int>(b"MPIABI_MODE_NOSUCCEED\0").expect("symbol MPIABI_MODE_NOSUCCEED"),
                mpi_mode_rdonly: *lib.get::<c_int>(b"MPIABI_MODE_RDONLY\0").expect("symbol MPIABI_MODE_RDONLY"),
                mpi_mode_rdwr: *lib.get::<c_int>(b"MPIABI_MODE_RDWR\0").expect("symbol MPIABI_MODE_RDWR"),
                mpi_mode_sequential: *lib.get::<c_int>(b"MPIABI_MODE_SEQUENTIAL\0").expect("symbol MPIABI_MODE_SEQUENTIAL"),
                mpi_mode_unique_open: *lib.get::<c_int>(b"MPIABI_MODE_UNIQUE_OPEN\0").expect("symbol MPIABI_MODE_UNIQUE_OPEN"),
                mpi_mode_wronly: *lib.get::<c_int>(b"MPIABI_MODE_WRONLY\0").expect("symbol MPIABI_MODE_WRONLY"),
                mpi_order_c: *lib.get::<c_int>(b"MPIABI_ORDER_C\0").expect("symbol MPIABI_ORDER_C"),
                mpi_order_fortran: *lib.get::<c_int>(b"MPIABI_ORDER_FORTRAN\0").expect("symbol MPIABI_ORDER_FORTRAN"),
                mpi_seek_cur: *lib.get::<c_int>(b"MPIABI_SEEK_CUR\0").expect("symbol MPIABI_SEEK_CUR"),
                mpi_seek_end: *lib.get::<c_int>(b"MPIABI_SEEK_END\0").expect("symbol MPIABI_SEEK_END"),
                mpi_seek_set: *lib.get::<c_int>(b"MPIABI_SEEK_SET\0").expect("symbol MPIABI_SEEK_SET"),
                mpi_thread_funneled: *lib.get::<c_int>(b"MPIABI_THREAD_FUNNELED\0").expect("symbol MPIABI_THREAD_FUNNELED"),
                mpi_thread_multiple: *lib.get::<c_int>(b"MPIABI_THREAD_MULTIPLE\0").expect("symbol MPIABI_THREAD_MULTIPLE"),
                mpi_thread_serialized: *lib.get::<c_int>(b"MPIABI_THREAD_SERIALIZED\0").expect("symbol MPIABI_THREAD_SERIALIZED"),
                mpi_thread_single: *lib.get::<c_int>(b"MPIABI_THREAD_SINGLE\0").expect("symbol MPIABI_THREAD_SINGLE"),
                mpi_typeclass_complex: *lib.get::<c_int>(b"MPIABI_TYPECLASS_COMPLEX\0").expect("symbol MPIABI_TYPECLASS_COMPLEX"),
                mpi_typeclass_integer: *lib.get::<c_int>(b"MPIABI_TYPECLASS_INTEGER\0").expect("symbol MPIABI_TYPECLASS_INTEGER"),
                mpi_typeclass_real: *lib.get::<c_int>(b"MPIABI_TYPECLASS_REAL\0").expect("symbol MPIABI_TYPECLASS_REAL"),
                mpi_win_flavor_allocate: *lib.get::<c_int>(b"MPIABI_WIN_FLAVOR_ALLOCATE\0").expect("symbol MPIABI_WIN_FLAVOR_ALLOCATE"),
                mpi_win_flavor_create: *lib.get::<c_int>(b"MPIABI_WIN_FLAVOR_CREATE\0").expect("symbol MPIABI_WIN_FLAVOR_CREATE"),
                mpi_win_flavor_dynamic: *lib.get::<c_int>(b"MPIABI_WIN_FLAVOR_DYNAMIC\0").expect("symbol MPIABI_WIN_FLAVOR_DYNAMIC"),
                mpi_win_flavor_shared: *lib.get::<c_int>(b"MPIABI_WIN_FLAVOR_SHARED\0").expect("symbol MPIABI_WIN_FLAVOR_SHARED"),
                mpi_win_separate: *lib.get::<c_int>(b"MPIABI_WIN_SEPARATE\0").expect("symbol MPIABI_WIN_SEPARATE"),
                mpi_win_unified: *lib.get::<c_int>(b"MPIABI_WIN_UNIFIED\0").expect("symbol MPIABI_WIN_UNIFIED"),
                mpi_argv_null: *lib.get::<*mut *mut c_char>(b"MPIABI_ARGV_NULL\0").expect("symbol MPIABI_ARGV_NULL"),
                mpi_argvs_null: *lib.get::<*mut *mut *mut c_char>(b"MPIABI_ARGVS_NULL\0").expect("symbol MPIABI_ARGVS_NULL"),
                mpi_errcodes_ignore: *lib.get::<*mut c_int>(b"MPIABI_ERRCODES_IGNORE\0").expect("symbol MPIABI_ERRCODES_IGNORE"),
                mpi_unweighted: *lib.get::<*mut c_int>(b"MPIABI_UNWEIGHTED\0").expect("symbol MPIABI_UNWEIGHTED"),
                mpi_weights_empty: *lib.get::<*mut c_int>(b"MPIABI_WEIGHTS_EMPTY\0").expect("symbol MPIABI_WEIGHTS_EMPTY"),
                mpi_bottom: *lib.get::<*mut c_void>(b"MPIABI_BOTTOM\0").expect("symbol MPIABI_BOTTOM"),
                mpi_in_place: *lib.get::<*mut c_void>(b"MPIABI_IN_PLACE\0").expect("symbol MPIABI_IN_PLACE"),
                mpi_comm_null: *lib.get::<MPI_Comm>(b"MPIABI_COMM_NULL\0").expect("symbol MPIABI_COMM_NULL"),
                mpi_comm_self: *lib.get::<MPI_Comm>(b"MPIABI_COMM_SELF\0").expect("symbol MPIABI_COMM_SELF"),
                mpi_comm_world: *lib.get::<MPI_Comm>(b"MPIABI_COMM_WORLD\0").expect("symbol MPIABI_COMM_WORLD"),
                mpi_comm_dup_fn: *lib.get::<MPI_Comm_copy_attr_function>(b"MPIABI_COMM_DUP_FN\0").expect("symbol MPIABI_COMM_DUP_FN"),
                mpi_comm_null_copy_fn: *lib.get::<MPI_Comm_copy_attr_function>(b"MPIABI_COMM_NULL_COPY_FN\0").expect("symbol MPIABI_COMM_NULL_COPY_FN"),
                mpi_comm_null_delete_fn: *lib.get::<MPI_Comm_delete_attr_function>(b"MPIABI_COMM_NULL_DELETE_FN\0").expect("symbol MPIABI_COMM_NULL_DELETE_FN"),
                mpi_dup_fn: *lib.get::<MPI_Copy_function>(b"MPIABI_DUP_FN\0").expect("symbol MPIABI_DUP_FN"),
                mpi_null_copy_fn: *lib.get::<MPI_Copy_function>(b"MPIABI_NULL_COPY_FN\0").expect("symbol MPIABI_NULL_COPY_FN"),
                mpi_conversion_fn_null: *lib.get::<MPI_Datarep_conversion_function>(b"MPIABI_CONVERSION_FN_NULL\0").expect("symbol MPIABI_CONVERSION_FN_NULL"),
                mpi_2double_precision: *lib.get::<MPI_Datatype>(b"MPIABI_2DOUBLE_PRECISION\0").expect("symbol MPIABI_2DOUBLE_PRECISION"),
                mpi_2int: *lib.get::<MPI_Datatype>(b"MPIABI_2INT\0").expect("symbol MPIABI_2INT"),
                mpi_2integer: *lib.get::<MPI_Datatype>(b"MPIABI_2INTEGER\0").expect("symbol MPIABI_2INTEGER"),
                mpi_2real: *lib.get::<MPI_Datatype>(b"MPIABI_2REAL\0").expect("symbol MPIABI_2REAL"),
                mpi_aint: *lib.get::<MPI_Datatype>(b"MPIABI_AINT\0").expect("symbol MPIABI_AINT"),
                mpi_byte: *lib.get::<MPI_Datatype>(b"MPIABI_BYTE\0").expect("symbol MPIABI_BYTE"),
                mpi_char: *lib.get::<MPI_Datatype>(b"MPIABI_CHAR\0").expect("symbol MPIABI_CHAR"),
                mpi_character: *lib.get::<MPI_Datatype>(b"MPIABI_CHARACTER\0").expect("symbol MPIABI_CHARACTER"),
                mpi_complex: *lib.get::<MPI_Datatype>(b"MPIABI_COMPLEX\0").expect("symbol MPIABI_COMPLEX"),
                mpi_complex16: *lib.get::<MPI_Datatype>(b"MPIABI_COMPLEX16\0").expect("symbol MPIABI_COMPLEX16"),
                mpi_complex32: *lib.get::<MPI_Datatype>(b"MPIABI_COMPLEX32\0").expect("symbol MPIABI_COMPLEX32"),
                mpi_complex8: *lib.get::<MPI_Datatype>(b"MPIABI_COMPLEX8\0").expect("symbol MPIABI_COMPLEX8"),
                mpi_count: *lib.get::<MPI_Datatype>(b"MPIABI_COUNT\0").expect("symbol MPIABI_COUNT"),
                mpi_cxx_bool: *lib.get::<MPI_Datatype>(b"MPIABI_CXX_BOOL\0").expect("symbol MPIABI_CXX_BOOL"),
                mpi_cxx_double_complex: *lib.get::<MPI_Datatype>(b"MPIABI_CXX_DOUBLE_COMPLEX\0").expect("symbol MPIABI_CXX_DOUBLE_COMPLEX"),
                mpi_cxx_float_complex: *lib.get::<MPI_Datatype>(b"MPIABI_CXX_FLOAT_COMPLEX\0").expect("symbol MPIABI_CXX_FLOAT_COMPLEX"),
                mpi_cxx_long_double_complex: *lib.get::<MPI_Datatype>(b"MPIABI_CXX_LONG_DOUBLE_COMPLEX\0").expect("symbol MPIABI_CXX_LONG_DOUBLE_COMPLEX"),
                mpi_c_bool: *lib.get::<MPI_Datatype>(b"MPIABI_C_BOOL\0").expect("symbol MPIABI_C_BOOL"),
                mpi_c_complex: *lib.get::<MPI_Datatype>(b"MPIABI_C_COMPLEX\0").expect("symbol MPIABI_C_COMPLEX"),
                mpi_c_double_complex: *lib.get::<MPI_Datatype>(b"MPIABI_C_DOUBLE_COMPLEX\0").expect("symbol MPIABI_C_DOUBLE_COMPLEX"),
                mpi_c_float_complex: *lib.get::<MPI_Datatype>(b"MPIABI_C_FLOAT_COMPLEX\0").expect("symbol MPIABI_C_FLOAT_COMPLEX"),
                mpi_c_long_double_complex: *lib.get::<MPI_Datatype>(b"MPIABI_C_LONG_DOUBLE_COMPLEX\0").expect("symbol MPIABI_C_LONG_DOUBLE_COMPLEX"),
                mpi_datatype_null: *lib.get::<MPI_Datatype>(b"MPIABI_DATATYPE_NULL\0").expect("symbol MPIABI_DATATYPE_NULL"),
                mpi_double: *lib.get::<MPI_Datatype>(b"MPIABI_DOUBLE\0").expect("symbol MPIABI_DOUBLE"),
                mpi_double_complex: *lib.get::<MPI_Datatype>(b"MPIABI_DOUBLE_COMPLEX\0").expect("symbol MPIABI_DOUBLE_COMPLEX"),
                mpi_double_int: *lib.get::<MPI_Datatype>(b"MPIABI_DOUBLE_INT\0").expect("symbol MPIABI_DOUBLE_INT"),
                mpi_double_precision: *lib.get::<MPI_Datatype>(b"MPIABI_DOUBLE_PRECISION\0").expect("symbol MPIABI_DOUBLE_PRECISION"),
                mpi_float: *lib.get::<MPI_Datatype>(b"MPIABI_FLOAT\0").expect("symbol MPIABI_FLOAT"),
                mpi_float_int: *lib.get::<MPI_Datatype>(b"MPIABI_FLOAT_INT\0").expect("symbol MPIABI_FLOAT_INT"),
                mpi_int: *lib.get::<MPI_Datatype>(b"MPIABI_INT\0").expect("symbol MPIABI_INT"),
                mpi_int16_t: *lib.get::<MPI_Datatype>(b"MPIABI_INT16_T\0").expect("symbol MPIABI_INT16_T"),
                mpi_int32_t: *lib.get::<MPI_Datatype>(b"MPIABI_INT32_T\0").expect("symbol MPIABI_INT32_T"),
                mpi_int64_t: *lib.get::<MPI_Datatype>(b"MPIABI_INT64_T\0").expect("symbol MPIABI_INT64_T"),
                mpi_int8_t: *lib.get::<MPI_Datatype>(b"MPIABI_INT8_T\0").expect("symbol MPIABI_INT8_T"),
                mpi_integer: *lib.get::<MPI_Datatype>(b"MPIABI_INTEGER\0").expect("symbol MPIABI_INTEGER"),
                mpi_integer1: *lib.get::<MPI_Datatype>(b"MPIABI_INTEGER1\0").expect("symbol MPIABI_INTEGER1"),
                mpi_integer2: *lib.get::<MPI_Datatype>(b"MPIABI_INTEGER2\0").expect("symbol MPIABI_INTEGER2"),
                mpi_integer4: *lib.get::<MPI_Datatype>(b"MPIABI_INTEGER4\0").expect("symbol MPIABI_INTEGER4"),
                mpi_integer8: *lib.get::<MPI_Datatype>(b"MPIABI_INTEGER8\0").expect("symbol MPIABI_INTEGER8"),
                mpi_logical: *lib.get::<MPI_Datatype>(b"MPIABI_LOGICAL\0").expect("symbol MPIABI_LOGICAL"),
                mpi_long: *lib.get::<MPI_Datatype>(b"MPIABI_LONG\0").expect("symbol MPIABI_LONG"),
                mpi_long_double: *lib.get::<MPI_Datatype>(b"MPIABI_LONG_DOUBLE\0").expect("symbol MPIABI_LONG_DOUBLE"),
                mpi_long_double_int: *lib.get::<MPI_Datatype>(b"MPIABI_LONG_DOUBLE_INT\0").expect("symbol MPIABI_LONG_DOUBLE_INT"),
                mpi_long_int: *lib.get::<MPI_Datatype>(b"MPIABI_LONG_INT\0").expect("symbol MPIABI_LONG_INT"),
                mpi_long_long: *lib.get::<MPI_Datatype>(b"MPIABI_LONG_LONG\0").expect("symbol MPIABI_LONG_LONG"),
                mpi_long_long_int: *lib.get::<MPI_Datatype>(b"MPIABI_LONG_LONG_INT\0").expect("symbol MPIABI_LONG_LONG_INT"),
                mpi_offset: *lib.get::<MPI_Datatype>(b"MPIABI_OFFSET\0").expect("symbol MPIABI_OFFSET"),
                mpi_packed: *lib.get::<MPI_Datatype>(b"MPIABI_PACKED\0").expect("symbol MPIABI_PACKED"),
                mpi_real: *lib.get::<MPI_Datatype>(b"MPIABI_REAL\0").expect("symbol MPIABI_REAL"),
                mpi_real16: *lib.get::<MPI_Datatype>(b"MPIABI_REAL16\0").expect("symbol MPIABI_REAL16"),
                mpi_real4: *lib.get::<MPI_Datatype>(b"MPIABI_REAL4\0").expect("symbol MPIABI_REAL4"),
                mpi_real8: *lib.get::<MPI_Datatype>(b"MPIABI_REAL8\0").expect("symbol MPIABI_REAL8"),
                mpi_short: *lib.get::<MPI_Datatype>(b"MPIABI_SHORT\0").expect("symbol MPIABI_SHORT"),
                mpi_short_int: *lib.get::<MPI_Datatype>(b"MPIABI_SHORT_INT\0").expect("symbol MPIABI_SHORT_INT"),
                mpi_signed_char: *lib.get::<MPI_Datatype>(b"MPIABI_SIGNED_CHAR\0").expect("symbol MPIABI_SIGNED_CHAR"),
                mpi_uint16_t: *lib.get::<MPI_Datatype>(b"MPIABI_UINT16_T\0").expect("symbol MPIABI_UINT16_T"),
                mpi_uint32_t: *lib.get::<MPI_Datatype>(b"MPIABI_UINT32_T\0").expect("symbol MPIABI_UINT32_T"),
                mpi_uint64_t: *lib.get::<MPI_Datatype>(b"MPIABI_UINT64_T\0").expect("symbol MPIABI_UINT64_T"),
                mpi_uint8_t: *lib.get::<MPI_Datatype>(b"MPIABI_UINT8_T\0").expect("symbol MPIABI_UINT8_T"),
                mpi_unsigned: *lib.get::<MPI_Datatype>(b"MPIABI_UNSIGNED\0").expect("symbol MPIABI_UNSIGNED"),
                mpi_unsigned_char: *lib.get::<MPI_Datatype>(b"MPIABI_UNSIGNED_CHAR\0").expect("symbol MPIABI_UNSIGNED_CHAR"),
                mpi_unsigned_long: *lib.get::<MPI_Datatype>(b"MPIABI_UNSIGNED_LONG\0").expect("symbol MPIABI_UNSIGNED_LONG"),
                mpi_unsigned_long_long: *lib.get::<MPI_Datatype>(b"MPIABI_UNSIGNED_LONG_LONG\0").expect("symbol MPIABI_UNSIGNED_LONG_LONG"),
                mpi_unsigned_short: *lib.get::<MPI_Datatype>(b"MPIABI_UNSIGNED_SHORT\0").expect("symbol MPIABI_UNSIGNED_SHORT"),
                mpi_wchar: *lib.get::<MPI_Datatype>(b"MPIABI_WCHAR\0").expect("symbol MPIABI_WCHAR"),
                mpi_null_delete_fn: *lib.get::<MPI_Delete_function>(b"MPIABI_NULL_DELETE_FN\0").expect("symbol MPIABI_NULL_DELETE_FN"),
                mpi_errhandler_null: *lib.get::<MPI_Errhandler>(b"MPIABI_ERRHANDLER_NULL\0").expect("symbol MPIABI_ERRHANDLER_NULL"),
                mpi_errors_are_fatal: *lib.get::<MPI_Errhandler>(b"MPIABI_ERRORS_ARE_FATAL\0").expect("symbol MPIABI_ERRORS_ARE_FATAL"),
                mpi_errors_return: *lib.get::<MPI_Errhandler>(b"MPIABI_ERRORS_RETURN\0").expect("symbol MPIABI_ERRORS_RETURN"),
                mpi_file_null: *lib.get::<MPI_File>(b"MPIABI_FILE_NULL\0").expect("symbol MPIABI_FILE_NULL"),
                mpi_f_status_ignore: *lib.get::<*mut MPI_Fint>(b"MPIABI_F_STATUS_IGNORE\0").expect("symbol MPIABI_F_STATUS_IGNORE"),
                mpi_f_statuses_ignore: *lib.get::<*mut MPI_Fint>(b"MPIABI_F_STATUSES_IGNORE\0").expect("symbol MPIABI_F_STATUSES_IGNORE"),
                mpi_group_empty: *lib.get::<MPI_Group>(b"MPIABI_GROUP_EMPTY\0").expect("symbol MPIABI_GROUP_EMPTY"),
                mpi_group_null: *lib.get::<MPI_Group>(b"MPIABI_GROUP_NULL\0").expect("symbol MPIABI_GROUP_NULL"),
                mpi_info_env: *lib.get::<MPI_Info>(b"MPIABI_INFO_ENV\0").expect("symbol MPIABI_INFO_ENV"),
                mpi_info_null: *lib.get::<MPI_Info>(b"MPIABI_INFO_NULL\0").expect("symbol MPIABI_INFO_NULL"),
                mpi_message_no_proc: *lib.get::<MPI_Message>(b"MPIABI_MESSAGE_NO_PROC\0").expect("symbol MPIABI_MESSAGE_NO_PROC"),
                mpi_message_null: *lib.get::<MPI_Message>(b"MPIABI_MESSAGE_NULL\0").expect("symbol MPIABI_MESSAGE_NULL"),
                mpi_displacement_current: *lib.get::<MPI_Offset>(b"MPIABI_DISPLACEMENT_CURRENT\0").expect("symbol MPIABI_DISPLACEMENT_CURRENT"),
                mpi_band: *lib.get::<MPI_Op>(b"MPIABI_BAND\0").expect("symbol MPIABI_BAND"),
                mpi_bor: *lib.get::<MPI_Op>(b"MPIABI_BOR\0").expect("symbol MPIABI_BOR"),
                mpi_bxor: *lib.get::<MPI_Op>(b"MPIABI_BXOR\0").expect("symbol MPIABI_BXOR"),
                mpi_land: *lib.get::<MPI_Op>(b"MPIABI_LAND\0").expect("symbol MPIABI_LAND"),
                mpi_lor: *lib.get::<MPI_Op>(b"MPIABI_LOR\0").expect("symbol MPIABI_LOR"),
                mpi_lxor: *lib.get::<MPI_Op>(b"MPIABI_LXOR\0").expect("symbol MPIABI_LXOR"),
                mpi_max: *lib.get::<MPI_Op>(b"MPIABI_MAX\0").expect("symbol MPIABI_MAX"),
                mpi_maxloc: *lib.get::<MPI_Op>(b"MPIABI_MAXLOC\0").expect("symbol MPIABI_MAXLOC"),
                mpi_min: *lib.get::<MPI_Op>(b"MPIABI_MIN\0").expect("symbol MPIABI_MIN"),
                mpi_minloc: *lib.get::<MPI_Op>(b"MPIABI_MINLOC\0").expect("symbol MPIABI_MINLOC"),
                mpi_no_op: *lib.get::<MPI_Op>(b"MPIABI_NO_OP\0").expect("symbol MPIABI_NO_OP"),
                mpi_op_null: *lib.get::<MPI_Op>(b"MPIABI_OP_NULL\0").expect("symbol MPIABI_OP_NULL"),
                mpi_prod: *lib.get::<MPI_Op>(b"MPIABI_PROD\0").expect("symbol MPIABI_PROD"),
                mpi_replace: *lib.get::<MPI_Op>(b"MPIABI_REPLACE\0").expect("symbol MPIABI_REPLACE"),
                mpi_sum: *lib.get::<MPI_Op>(b"MPIABI_SUM\0").expect("symbol MPIABI_SUM"),
                mpi_request_null: *lib.get::<MPI_Request>(b"MPIABI_REQUEST_NULL\0").expect("symbol MPIABI_REQUEST_NULL"),
                mpi_status_ignore: *lib.get::<*mut MPI_Status>(b"MPIABI_STATUS_IGNORE\0").expect("symbol MPIABI_STATUS_IGNORE"),
                mpi_statuses_ignore: *lib.get::<*mut MPI_Status>(b"MPIABI_STATUSES_IGNORE\0").expect("symbol MPIABI_STATUSES_IGNORE"),
                mpi_type_dup_fn: *lib.get::<MPI_Type_copy_attr_function>(b"MPIABI_TYPE_DUP_FN\0").expect("symbol MPIABI_TYPE_DUP_FN"),
                mpi_type_null_copy_fn: *lib.get::<MPI_Type_copy_attr_function>(b"MPIABI_TYPE_NULL_COPY_FN\0").expect("symbol MPIABI_TYPE_NULL_COPY_FN"),
                mpi_type_null_delete_fn: *lib.get::<MPI_Type_delete_attr_function>(b"MPIABI_TYPE_NULL_DELETE_FN\0").expect("symbol MPIABI_TYPE_NULL_DELETE_FN"),
                mpi_win_null: *lib.get::<MPI_Win>(b"MPIABI_WIN_NULL\0").expect("symbol MPIABI_WIN_NULL"),
                mpi_win_dup_fn: *lib.get::<MPI_Win_copy_attr_function>(b"MPIABI_WIN_DUP_FN\0").expect("symbol MPIABI_WIN_DUP_FN"),
                mpi_win_null_copy_fn: *lib.get::<MPI_Win_copy_attr_function>(b"MPIABI_WIN_NULL_COPY_FN\0").expect("symbol MPIABI_WIN_NULL_COPY_FN"),
                mpi_win_null_delete_fn: *lib.get::<MPI_Win_delete_attr_function>(b"MPIABI_WIN_NULL_DELETE_FN\0").expect("symbol MPIABI_WIN_NULL_DELETE_FN"),
            }
        }
    })
}

pub fn RSMPI_ANY_SOURCE_fn() -> c_int {
    get_constants().mpi_any_source
}

pub fn RSMPI_ANY_TAG_fn() -> c_int {
    get_constants().mpi_any_tag
}

pub fn RSMPI_PROC_NULL_fn() -> c_int {
    get_constants().mpi_proc_null
}

pub fn RSMPI_ROOT_fn() -> c_int {
    get_constants().mpi_root
}

pub fn RSMPI_CART_fn() -> c_int {
    get_constants().mpi_cart
}

pub fn RSMPI_DIST_GRAPH_fn() -> c_int {
    get_constants().mpi_dist_graph
}

pub fn RSMPI_GRAPH_fn() -> c_int {
    get_constants().mpi_graph
}

pub fn RSMPI_CONGRUENT_fn() -> c_int {
    get_constants().mpi_congruent
}

pub fn RSMPI_IDENT_fn() -> c_int {
    get_constants().mpi_ident
}

pub fn RSMPI_SIMILAR_fn() -> c_int {
    get_constants().mpi_similar
}

pub fn RSMPI_UNEQUAL_fn() -> c_int {
    get_constants().mpi_unequal
}

pub fn RSMPI_BSEND_OVERHEAD_fn() -> c_int {
    get_constants().mpi_bsend_overhead
}

pub fn RSMPI_KEYVAL_INVALID_fn() -> c_int {
    get_constants().mpi_keyval_invalid
}

pub fn RSMPI_UNDEFINED_fn() -> c_int {
    get_constants().mpi_undefined
}

pub fn RSMPI_APPNUM_fn() -> c_int {
    get_constants().mpi_appnum
}

pub fn RSMPI_HOST_fn() -> c_int {
    get_constants().mpi_host
}

pub fn RSMPI_IO_fn() -> c_int {
    get_constants().mpi_io
}

pub fn RSMPI_LASTUSEDCODE_fn() -> c_int {
    get_constants().mpi_lastusedcode
}

pub fn RSMPI_TAG_UB_fn() -> c_int {
    get_constants().mpi_tag_ub
}

pub fn RSMPI_UNIVERSE_SIZE_fn() -> c_int {
    get_constants().mpi_universe_size
}

pub fn RSMPI_WIN_BASE_fn() -> c_int {
    get_constants().mpi_win_base
}

pub fn RSMPI_WIN_CREATE_FLAVOR_fn() -> c_int {
    get_constants().mpi_win_create_flavor
}

pub fn RSMPI_WIN_DISP_UNIT_fn() -> c_int {
    get_constants().mpi_win_disp_unit
}

pub fn RSMPI_WIN_MODEL_fn() -> c_int {
    get_constants().mpi_win_model
}

pub fn RSMPI_WIN_SIZE_fn() -> c_int {
    get_constants().mpi_win_size
}

pub fn RSMPI_WTIME_IS_GLOBAL_fn() -> c_int {
    get_constants().mpi_wtime_is_global
}

pub fn RSMPI_COMBINER_CONTIGUOUS_fn() -> c_int {
    get_constants().mpi_combiner_contiguous
}

pub fn RSMPI_COMBINER_DARRAY_fn() -> c_int {
    get_constants().mpi_combiner_darray
}

pub fn RSMPI_COMBINER_DUP_fn() -> c_int {
    get_constants().mpi_combiner_dup
}

pub fn RSMPI_COMBINER_F90_COMPLEX_fn() -> c_int {
    get_constants().mpi_combiner_f90_complex
}

pub fn RSMPI_COMBINER_F90_INTEGER_fn() -> c_int {
    get_constants().mpi_combiner_f90_integer
}

pub fn RSMPI_COMBINER_F90_REAL_fn() -> c_int {
    get_constants().mpi_combiner_f90_real
}

pub fn RSMPI_COMBINER_HINDEXED_fn() -> c_int {
    get_constants().mpi_combiner_hindexed
}

pub fn RSMPI_COMBINER_HINDEXED_BLOCK_fn() -> c_int {
    get_constants().mpi_combiner_hindexed_block
}

pub fn RSMPI_COMBINER_HVECTOR_fn() -> c_int {
    get_constants().mpi_combiner_hvector
}

pub fn RSMPI_COMBINER_INDEXED_fn() -> c_int {
    get_constants().mpi_combiner_indexed
}

pub fn RSMPI_COMBINER_INDEXED_BLOCK_fn() -> c_int {
    get_constants().mpi_combiner_indexed_block
}

pub fn RSMPI_COMBINER_NAMED_fn() -> c_int {
    get_constants().mpi_combiner_named
}

pub fn RSMPI_COMBINER_RESIZED_fn() -> c_int {
    get_constants().mpi_combiner_resized
}

pub fn RSMPI_COMBINER_STRUCT_fn() -> c_int {
    get_constants().mpi_combiner_struct
}

pub fn RSMPI_COMBINER_SUBARRAY_fn() -> c_int {
    get_constants().mpi_combiner_subarray
}

pub fn RSMPI_COMBINER_VECTOR_fn() -> c_int {
    get_constants().mpi_combiner_vector
}

pub fn RSMPI_COMM_TYPE_SHARED_fn() -> c_int {
    get_constants().mpi_comm_type_shared
}

pub fn RSMPI_DISTRIBUTE_BLOCK_fn() -> c_int {
    get_constants().mpi_distribute_block
}

pub fn RSMPI_DISTRIBUTE_CYCLIC_fn() -> c_int {
    get_constants().mpi_distribute_cyclic
}

pub fn RSMPI_DISTRIBUTE_DFLT_DARG_fn() -> c_int {
    get_constants().mpi_distribute_dflt_darg
}

pub fn RSMPI_DISTRIBUTE_NONE_fn() -> c_int {
    get_constants().mpi_distribute_none
}

pub fn RSMPI_ERR_ACCESS_fn() -> c_int {
    get_constants().mpi_err_access
}

pub fn RSMPI_ERR_AMODE_fn() -> c_int {
    get_constants().mpi_err_amode
}

pub fn RSMPI_ERR_ARG_fn() -> c_int {
    get_constants().mpi_err_arg
}

pub fn RSMPI_ERR_ASSERT_fn() -> c_int {
    get_constants().mpi_err_assert
}

pub fn RSMPI_ERR_BAD_FILE_fn() -> c_int {
    get_constants().mpi_err_bad_file
}

pub fn RSMPI_ERR_BASE_fn() -> c_int {
    get_constants().mpi_err_base
}

pub fn RSMPI_ERR_BUFFER_fn() -> c_int {
    get_constants().mpi_err_buffer
}

pub fn RSMPI_ERR_COMM_fn() -> c_int {
    get_constants().mpi_err_comm
}

pub fn RSMPI_ERR_CONVERSION_fn() -> c_int {
    get_constants().mpi_err_conversion
}

pub fn RSMPI_ERR_COUNT_fn() -> c_int {
    get_constants().mpi_err_count
}

pub fn RSMPI_ERR_DIMS_fn() -> c_int {
    get_constants().mpi_err_dims
}

pub fn RSMPI_ERR_DISP_fn() -> c_int {
    get_constants().mpi_err_disp
}

pub fn RSMPI_ERR_DUP_DATAREP_fn() -> c_int {
    get_constants().mpi_err_dup_datarep
}

pub fn RSMPI_ERR_FILE_fn() -> c_int {
    get_constants().mpi_err_file
}

pub fn RSMPI_ERR_FILE_EXISTS_fn() -> c_int {
    get_constants().mpi_err_file_exists
}

pub fn RSMPI_ERR_FILE_IN_USE_fn() -> c_int {
    get_constants().mpi_err_file_in_use
}

pub fn RSMPI_ERR_GROUP_fn() -> c_int {
    get_constants().mpi_err_group
}

pub fn RSMPI_ERR_INFO_fn() -> c_int {
    get_constants().mpi_err_info
}

pub fn RSMPI_ERR_INFO_KEY_fn() -> c_int {
    get_constants().mpi_err_info_key
}

pub fn RSMPI_ERR_INFO_NOKEY_fn() -> c_int {
    get_constants().mpi_err_info_nokey
}

pub fn RSMPI_ERR_INFO_VALUE_fn() -> c_int {
    get_constants().mpi_err_info_value
}

pub fn RSMPI_ERR_INTERN_fn() -> c_int {
    get_constants().mpi_err_intern
}

pub fn RSMPI_ERR_IN_STATUS_fn() -> c_int {
    get_constants().mpi_err_in_status
}

pub fn RSMPI_ERR_IO_fn() -> c_int {
    get_constants().mpi_err_io
}

pub fn RSMPI_ERR_KEYVAL_fn() -> c_int {
    get_constants().mpi_err_keyval
}

pub fn RSMPI_ERR_LASTCODE_fn() -> c_int {
    get_constants().mpi_err_lastcode
}

pub fn RSMPI_ERR_LOCKTYPE_fn() -> c_int {
    get_constants().mpi_err_locktype
}

pub fn RSMPI_ERR_NAME_fn() -> c_int {
    get_constants().mpi_err_name
}

pub fn RSMPI_ERR_NOT_SAME_fn() -> c_int {
    get_constants().mpi_err_not_same
}

pub fn RSMPI_ERR_NO_MEM_fn() -> c_int {
    get_constants().mpi_err_no_mem
}

pub fn RSMPI_ERR_NO_SPACE_fn() -> c_int {
    get_constants().mpi_err_no_space
}

pub fn RSMPI_ERR_NO_SUCH_FILE_fn() -> c_int {
    get_constants().mpi_err_no_such_file
}

pub fn RSMPI_ERR_OP_fn() -> c_int {
    get_constants().mpi_err_op
}

pub fn RSMPI_ERR_OTHER_fn() -> c_int {
    get_constants().mpi_err_other
}

pub fn RSMPI_ERR_PENDING_fn() -> c_int {
    get_constants().mpi_err_pending
}

pub fn RSMPI_ERR_PORT_fn() -> c_int {
    get_constants().mpi_err_port
}

pub fn RSMPI_ERR_QUOTA_fn() -> c_int {
    get_constants().mpi_err_quota
}

pub fn RSMPI_ERR_RANK_fn() -> c_int {
    get_constants().mpi_err_rank
}

pub fn RSMPI_ERR_READ_ONLY_fn() -> c_int {
    get_constants().mpi_err_read_only
}

pub fn RSMPI_ERR_REQUEST_fn() -> c_int {
    get_constants().mpi_err_request
}

pub fn RSMPI_ERR_RMA_ATTACH_fn() -> c_int {
    get_constants().mpi_err_rma_attach
}

pub fn RSMPI_ERR_RMA_CONFLICT_fn() -> c_int {
    get_constants().mpi_err_rma_conflict
}

pub fn RSMPI_ERR_RMA_FLAVOR_fn() -> c_int {
    get_constants().mpi_err_rma_flavor
}

pub fn RSMPI_ERR_RMA_RANGE_fn() -> c_int {
    get_constants().mpi_err_rma_range
}

pub fn RSMPI_ERR_RMA_SHARED_fn() -> c_int {
    get_constants().mpi_err_rma_shared
}

pub fn RSMPI_ERR_RMA_SYNC_fn() -> c_int {
    get_constants().mpi_err_rma_sync
}

pub fn RSMPI_ERR_ROOT_fn() -> c_int {
    get_constants().mpi_err_root
}

pub fn RSMPI_ERR_SERVICE_fn() -> c_int {
    get_constants().mpi_err_service
}

pub fn RSMPI_ERR_SIZE_fn() -> c_int {
    get_constants().mpi_err_size
}

pub fn RSMPI_ERR_SPAWN_fn() -> c_int {
    get_constants().mpi_err_spawn
}

pub fn RSMPI_ERR_TAG_fn() -> c_int {
    get_constants().mpi_err_tag
}

pub fn RSMPI_ERR_TOPOLOGY_fn() -> c_int {
    get_constants().mpi_err_topology
}

pub fn RSMPI_ERR_TRUNCATE_fn() -> c_int {
    get_constants().mpi_err_truncate
}

pub fn RSMPI_ERR_TYPE_fn() -> c_int {
    get_constants().mpi_err_type
}

pub fn RSMPI_ERR_UNKNOWN_fn() -> c_int {
    get_constants().mpi_err_unknown
}

pub fn RSMPI_ERR_UNSUPPORTED_DATAREP_fn() -> c_int {
    get_constants().mpi_err_unsupported_datarep
}

pub fn RSMPI_ERR_UNSUPPORTED_OPERATION_fn() -> c_int {
    get_constants().mpi_err_unsupported_operation
}

pub fn RSMPI_ERR_WIN_fn() -> c_int {
    get_constants().mpi_err_win
}

pub fn RSMPI_SUCCESS_fn() -> c_int {
    get_constants().mpi_success
}

pub fn RSMPI_LOCK_EXCLUSIVE_fn() -> c_int {
    get_constants().mpi_lock_exclusive
}

pub fn RSMPI_LOCK_SHARED_fn() -> c_int {
    get_constants().mpi_lock_shared
}

pub fn RSMPI_MODE_APPEND_fn() -> c_int {
    get_constants().mpi_mode_append
}

pub fn RSMPI_MODE_CREATE_fn() -> c_int {
    get_constants().mpi_mode_create
}

pub fn RSMPI_MODE_DELETE_ON_CLOSE_fn() -> c_int {
    get_constants().mpi_mode_delete_on_close
}

pub fn RSMPI_MODE_EXCL_fn() -> c_int {
    get_constants().mpi_mode_excl
}

pub fn RSMPI_MODE_NOCHECK_fn() -> c_int {
    get_constants().mpi_mode_nocheck
}

pub fn RSMPI_MODE_NOPRECEDE_fn() -> c_int {
    get_constants().mpi_mode_noprecede
}

pub fn RSMPI_MODE_NOPUT_fn() -> c_int {
    get_constants().mpi_mode_noput
}

pub fn RSMPI_MODE_NOSTORE_fn() -> c_int {
    get_constants().mpi_mode_nostore
}

pub fn RSMPI_MODE_NOSUCCEED_fn() -> c_int {
    get_constants().mpi_mode_nosucceed
}

pub fn RSMPI_MODE_RDONLY_fn() -> c_int {
    get_constants().mpi_mode_rdonly
}

pub fn RSMPI_MODE_RDWR_fn() -> c_int {
    get_constants().mpi_mode_rdwr
}

pub fn RSMPI_MODE_SEQUENTIAL_fn() -> c_int {
    get_constants().mpi_mode_sequential
}

pub fn RSMPI_MODE_UNIQUE_OPEN_fn() -> c_int {
    get_constants().mpi_mode_unique_open
}

pub fn RSMPI_MODE_WRONLY_fn() -> c_int {
    get_constants().mpi_mode_wronly
}

pub fn RSMPI_ORDER_C_fn() -> c_int {
    get_constants().mpi_order_c
}

pub fn RSMPI_ORDER_FORTRAN_fn() -> c_int {
    get_constants().mpi_order_fortran
}

pub fn RSMPI_SEEK_CUR_fn() -> c_int {
    get_constants().mpi_seek_cur
}

pub fn RSMPI_SEEK_END_fn() -> c_int {
    get_constants().mpi_seek_end
}

pub fn RSMPI_SEEK_SET_fn() -> c_int {
    get_constants().mpi_seek_set
}

pub fn RSMPI_THREAD_FUNNELED_fn() -> c_int {
    get_constants().mpi_thread_funneled
}

pub fn RSMPI_THREAD_MULTIPLE_fn() -> c_int {
    get_constants().mpi_thread_multiple
}

pub fn RSMPI_THREAD_SERIALIZED_fn() -> c_int {
    get_constants().mpi_thread_serialized
}

pub fn RSMPI_THREAD_SINGLE_fn() -> c_int {
    get_constants().mpi_thread_single
}

pub fn RSMPI_TYPECLASS_COMPLEX_fn() -> c_int {
    get_constants().mpi_typeclass_complex
}

pub fn RSMPI_TYPECLASS_INTEGER_fn() -> c_int {
    get_constants().mpi_typeclass_integer
}

pub fn RSMPI_TYPECLASS_REAL_fn() -> c_int {
    get_constants().mpi_typeclass_real
}

pub fn RSMPI_WIN_FLAVOR_ALLOCATE_fn() -> c_int {
    get_constants().mpi_win_flavor_allocate
}

pub fn RSMPI_WIN_FLAVOR_CREATE_fn() -> c_int {
    get_constants().mpi_win_flavor_create
}

pub fn RSMPI_WIN_FLAVOR_DYNAMIC_fn() -> c_int {
    get_constants().mpi_win_flavor_dynamic
}

pub fn RSMPI_WIN_FLAVOR_SHARED_fn() -> c_int {
    get_constants().mpi_win_flavor_shared
}

pub fn RSMPI_WIN_SEPARATE_fn() -> c_int {
    get_constants().mpi_win_separate
}

pub fn RSMPI_WIN_UNIFIED_fn() -> c_int {
    get_constants().mpi_win_unified
}

pub fn RSMPI_ARGV_NULL_fn() -> *mut *mut c_char {
    get_constants().mpi_argv_null
}

pub fn RSMPI_ARGVS_NULL_fn() -> *mut *mut *mut c_char {
    get_constants().mpi_argvs_null
}

pub fn RSMPI_ERRCODES_IGNORE_fn() -> *mut c_int {
    get_constants().mpi_errcodes_ignore
}

pub fn RSMPI_UNWEIGHTED_fn() -> *mut c_int {
    get_constants().mpi_unweighted
}

pub fn RSMPI_WEIGHTS_EMPTY_fn() -> *mut c_int {
    get_constants().mpi_weights_empty
}

pub fn RSMPI_BOTTOM_fn() -> *mut c_void {
    get_constants().mpi_bottom
}

pub fn RSMPI_IN_PLACE_fn() -> *mut c_void {
    get_constants().mpi_in_place
}

pub fn RSMPI_COMM_NULL_fn() -> MPI_Comm {
    get_constants().mpi_comm_null
}

pub fn RSMPI_COMM_SELF_fn() -> MPI_Comm {
    get_constants().mpi_comm_self
}

pub fn RSMPI_COMM_WORLD_fn() -> MPI_Comm {
    get_constants().mpi_comm_world
}

pub fn RSMPI_COMM_DUP_FN_fn() -> MPI_Comm_copy_attr_function {
    get_constants().mpi_comm_dup_fn
}

pub fn RSMPI_COMM_NULL_COPY_FN_fn() -> MPI_Comm_copy_attr_function {
    get_constants().mpi_comm_null_copy_fn
}

pub fn RSMPI_COMM_NULL_DELETE_FN_fn() -> MPI_Comm_delete_attr_function {
    get_constants().mpi_comm_null_delete_fn
}

pub fn RSMPI_DUP_FN_fn() -> MPI_Copy_function {
    get_constants().mpi_dup_fn
}

pub fn RSMPI_NULL_COPY_FN_fn() -> MPI_Copy_function {
    get_constants().mpi_null_copy_fn
}

pub fn RSMPI_CONVERSION_FN_NULL_fn() -> MPI_Datarep_conversion_function {
    get_constants().mpi_conversion_fn_null
}

pub fn RSMPI_2DOUBLE_PRECISION_fn() -> MPI_Datatype {
    get_constants().mpi_2double_precision
}

pub fn RSMPI_2INT_fn() -> MPI_Datatype {
    get_constants().mpi_2int
}

pub fn RSMPI_2INTEGER_fn() -> MPI_Datatype {
    get_constants().mpi_2integer
}

pub fn RSMPI_2REAL_fn() -> MPI_Datatype {
    get_constants().mpi_2real
}

pub fn RSMPI_AINT_fn() -> MPI_Datatype {
    get_constants().mpi_aint
}

pub fn RSMPI_BYTE_fn() -> MPI_Datatype {
    get_constants().mpi_byte
}

pub fn RSMPI_CHAR_fn() -> MPI_Datatype {
    get_constants().mpi_char
}

pub fn RSMPI_CHARACTER_fn() -> MPI_Datatype {
    get_constants().mpi_character
}

pub fn RSMPI_COMPLEX_fn() -> MPI_Datatype {
    get_constants().mpi_complex
}

pub fn RSMPI_COMPLEX16_fn() -> MPI_Datatype {
    get_constants().mpi_complex16
}

pub fn RSMPI_COMPLEX32_fn() -> MPI_Datatype {
    get_constants().mpi_complex32
}

pub fn RSMPI_COMPLEX8_fn() -> MPI_Datatype {
    get_constants().mpi_complex8
}

pub fn RSMPI_COUNT_fn() -> MPI_Datatype {
    get_constants().mpi_count
}

pub fn RSMPI_CXX_BOOL_fn() -> MPI_Datatype {
    get_constants().mpi_cxx_bool
}

pub fn RSMPI_CXX_DOUBLE_COMPLEX_fn() -> MPI_Datatype {
    get_constants().mpi_cxx_double_complex
}

pub fn RSMPI_CXX_FLOAT_COMPLEX_fn() -> MPI_Datatype {
    get_constants().mpi_cxx_float_complex
}

pub fn RSMPI_CXX_LONG_DOUBLE_COMPLEX_fn() -> MPI_Datatype {
    get_constants().mpi_cxx_long_double_complex
}

pub fn RSMPI_C_BOOL_fn() -> MPI_Datatype {
    get_constants().mpi_c_bool
}

pub fn RSMPI_C_COMPLEX_fn() -> MPI_Datatype {
    get_constants().mpi_c_complex
}

pub fn RSMPI_C_DOUBLE_COMPLEX_fn() -> MPI_Datatype {
    get_constants().mpi_c_double_complex
}

pub fn RSMPI_C_FLOAT_COMPLEX_fn() -> MPI_Datatype {
    get_constants().mpi_c_float_complex
}

pub fn RSMPI_C_LONG_DOUBLE_COMPLEX_fn() -> MPI_Datatype {
    get_constants().mpi_c_long_double_complex
}

pub fn RSMPI_DATATYPE_NULL_fn() -> MPI_Datatype {
    get_constants().mpi_datatype_null
}

pub fn RSMPI_DOUBLE_fn() -> MPI_Datatype {
    get_constants().mpi_double
}

pub fn RSMPI_DOUBLE_COMPLEX_fn() -> MPI_Datatype {
    get_constants().mpi_double_complex
}

pub fn RSMPI_DOUBLE_INT_fn() -> MPI_Datatype {
    get_constants().mpi_double_int
}

pub fn RSMPI_DOUBLE_PRECISION_fn() -> MPI_Datatype {
    get_constants().mpi_double_precision
}

pub fn RSMPI_FLOAT_fn() -> MPI_Datatype {
    get_constants().mpi_float
}

pub fn RSMPI_FLOAT_INT_fn() -> MPI_Datatype {
    get_constants().mpi_float_int
}

pub fn RSMPI_INT_fn() -> MPI_Datatype {
    get_constants().mpi_int
}

pub fn RSMPI_INT16_T_fn() -> MPI_Datatype {
    get_constants().mpi_int16_t
}

pub fn RSMPI_INT32_T_fn() -> MPI_Datatype {
    get_constants().mpi_int32_t
}

pub fn RSMPI_INT64_T_fn() -> MPI_Datatype {
    get_constants().mpi_int64_t
}

pub fn RSMPI_INT8_T_fn() -> MPI_Datatype {
    get_constants().mpi_int8_t
}

pub fn RSMPI_INTEGER_fn() -> MPI_Datatype {
    get_constants().mpi_integer
}

pub fn RSMPI_INTEGER1_fn() -> MPI_Datatype {
    get_constants().mpi_integer1
}

pub fn RSMPI_INTEGER2_fn() -> MPI_Datatype {
    get_constants().mpi_integer2
}

pub fn RSMPI_INTEGER4_fn() -> MPI_Datatype {
    get_constants().mpi_integer4
}

pub fn RSMPI_INTEGER8_fn() -> MPI_Datatype {
    get_constants().mpi_integer8
}

pub fn RSMPI_LOGICAL_fn() -> MPI_Datatype {
    get_constants().mpi_logical
}

pub fn RSMPI_LONG_fn() -> MPI_Datatype {
    get_constants().mpi_long
}

pub fn RSMPI_LONG_DOUBLE_fn() -> MPI_Datatype {
    get_constants().mpi_long_double
}

pub fn RSMPI_LONG_DOUBLE_INT_fn() -> MPI_Datatype {
    get_constants().mpi_long_double_int
}

pub fn RSMPI_LONG_INT_fn() -> MPI_Datatype {
    get_constants().mpi_long_int
}

pub fn RSMPI_LONG_LONG_fn() -> MPI_Datatype {
    get_constants().mpi_long_long
}

pub fn RSMPI_LONG_LONG_INT_fn() -> MPI_Datatype {
    get_constants().mpi_long_long_int
}

pub fn RSMPI_OFFSET_fn() -> MPI_Datatype {
    get_constants().mpi_offset
}

pub fn RSMPI_PACKED_fn() -> MPI_Datatype {
    get_constants().mpi_packed
}

pub fn RSMPI_REAL_fn() -> MPI_Datatype {
    get_constants().mpi_real
}

pub fn RSMPI_REAL16_fn() -> MPI_Datatype {
    get_constants().mpi_real16
}

pub fn RSMPI_REAL4_fn() -> MPI_Datatype {
    get_constants().mpi_real4
}

pub fn RSMPI_REAL8_fn() -> MPI_Datatype {
    get_constants().mpi_real8
}

pub fn RSMPI_SHORT_fn() -> MPI_Datatype {
    get_constants().mpi_short
}

pub fn RSMPI_SHORT_INT_fn() -> MPI_Datatype {
    get_constants().mpi_short_int
}

pub fn RSMPI_SIGNED_CHAR_fn() -> MPI_Datatype {
    get_constants().mpi_signed_char
}

pub fn RSMPI_UINT16_T_fn() -> MPI_Datatype {
    get_constants().mpi_uint16_t
}

pub fn RSMPI_UINT32_T_fn() -> MPI_Datatype {
    get_constants().mpi_uint32_t
}

pub fn RSMPI_UINT64_T_fn() -> MPI_Datatype {
    get_constants().mpi_uint64_t
}

pub fn RSMPI_UINT8_T_fn() -> MPI_Datatype {
    get_constants().mpi_uint8_t
}

pub fn RSMPI_UNSIGNED_fn() -> MPI_Datatype {
    get_constants().mpi_unsigned
}

pub fn RSMPI_UNSIGNED_CHAR_fn() -> MPI_Datatype {
    get_constants().mpi_unsigned_char
}

pub fn RSMPI_UNSIGNED_LONG_fn() -> MPI_Datatype {
    get_constants().mpi_unsigned_long
}

pub fn RSMPI_UNSIGNED_LONG_LONG_fn() -> MPI_Datatype {
    get_constants().mpi_unsigned_long_long
}

pub fn RSMPI_UNSIGNED_SHORT_fn() -> MPI_Datatype {
    get_constants().mpi_unsigned_short
}

pub fn RSMPI_WCHAR_fn() -> MPI_Datatype {
    get_constants().mpi_wchar
}

pub fn RSMPI_NULL_DELETE_FN_fn() -> MPI_Delete_function {
    get_constants().mpi_null_delete_fn
}

pub fn RSMPI_ERRHANDLER_NULL_fn() -> MPI_Errhandler {
    get_constants().mpi_errhandler_null
}

pub fn RSMPI_ERRORS_ARE_FATAL_fn() -> MPI_Errhandler {
    get_constants().mpi_errors_are_fatal
}

pub fn RSMPI_ERRORS_RETURN_fn() -> MPI_Errhandler {
    get_constants().mpi_errors_return
}

pub fn RSMPI_FILE_NULL_fn() -> MPI_File {
    get_constants().mpi_file_null
}

pub fn RSMPI_F_STATUS_IGNORE_fn() -> *mut MPI_Fint {
    get_constants().mpi_f_status_ignore
}

pub fn RSMPI_F_STATUSES_IGNORE_fn() -> *mut MPI_Fint {
    get_constants().mpi_f_statuses_ignore
}

pub fn RSMPI_GROUP_EMPTY_fn() -> MPI_Group {
    get_constants().mpi_group_empty
}

pub fn RSMPI_GROUP_NULL_fn() -> MPI_Group {
    get_constants().mpi_group_null
}

pub fn RSMPI_INFO_ENV_fn() -> MPI_Info {
    get_constants().mpi_info_env
}

pub fn RSMPI_INFO_NULL_fn() -> MPI_Info {
    get_constants().mpi_info_null
}

pub fn RSMPI_MESSAGE_NO_PROC_fn() -> MPI_Message {
    get_constants().mpi_message_no_proc
}

pub fn RSMPI_MESSAGE_NULL_fn() -> MPI_Message {
    get_constants().mpi_message_null
}

pub fn RSMPI_DISPLACEMENT_CURRENT_fn() -> MPI_Offset {
    get_constants().mpi_displacement_current
}

pub fn RSMPI_BAND_fn() -> MPI_Op {
    get_constants().mpi_band
}

pub fn RSMPI_BOR_fn() -> MPI_Op {
    get_constants().mpi_bor
}

pub fn RSMPI_BXOR_fn() -> MPI_Op {
    get_constants().mpi_bxor
}

pub fn RSMPI_LAND_fn() -> MPI_Op {
    get_constants().mpi_land
}

pub fn RSMPI_LOR_fn() -> MPI_Op {
    get_constants().mpi_lor
}

pub fn RSMPI_LXOR_fn() -> MPI_Op {
    get_constants().mpi_lxor
}

pub fn RSMPI_MAX_fn() -> MPI_Op {
    get_constants().mpi_max
}

pub fn RSMPI_MAXLOC_fn() -> MPI_Op {
    get_constants().mpi_maxloc
}

pub fn RSMPI_MIN_fn() -> MPI_Op {
    get_constants().mpi_min
}

pub fn RSMPI_MINLOC_fn() -> MPI_Op {
    get_constants().mpi_minloc
}

pub fn RSMPI_NO_OP_fn() -> MPI_Op {
    get_constants().mpi_no_op
}

pub fn RSMPI_OP_NULL_fn() -> MPI_Op {
    get_constants().mpi_op_null
}

pub fn RSMPI_PROD_fn() -> MPI_Op {
    get_constants().mpi_prod
}

pub fn RSMPI_REPLACE_fn() -> MPI_Op {
    get_constants().mpi_replace
}

pub fn RSMPI_SUM_fn() -> MPI_Op {
    get_constants().mpi_sum
}

pub fn RSMPI_REQUEST_NULL_fn() -> MPI_Request {
    get_constants().mpi_request_null
}

pub fn RSMPI_STATUS_IGNORE_fn() -> *mut MPI_Status {
    get_constants().mpi_status_ignore
}

pub fn RSMPI_STATUSES_IGNORE_fn() -> *mut MPI_Status {
    get_constants().mpi_statuses_ignore
}

pub fn RSMPI_TYPE_DUP_FN_fn() -> MPI_Type_copy_attr_function {
    get_constants().mpi_type_dup_fn
}

pub fn RSMPI_TYPE_NULL_COPY_FN_fn() -> MPI_Type_copy_attr_function {
    get_constants().mpi_type_null_copy_fn
}

pub fn RSMPI_TYPE_NULL_DELETE_FN_fn() -> MPI_Type_delete_attr_function {
    get_constants().mpi_type_null_delete_fn
}

pub fn RSMPI_WIN_NULL_fn() -> MPI_Win {
    get_constants().mpi_win_null
}

pub fn RSMPI_WIN_DUP_FN_fn() -> MPI_Win_copy_attr_function {
    get_constants().mpi_win_dup_fn
}

pub fn RSMPI_WIN_NULL_COPY_FN_fn() -> MPI_Win_copy_attr_function {
    get_constants().mpi_win_null_copy_fn
}

pub fn RSMPI_WIN_NULL_DELETE_FN_fn() -> MPI_Win_delete_attr_function {
    get_constants().mpi_win_null_delete_fn
}

pub fn RSMPI_ANY_SOURCE() -> c_int {
    get_constants().mpi_any_source
}

pub fn RSMPI_ANY_TAG() -> c_int {
    get_constants().mpi_any_tag
}

pub fn RSMPI_PROC_NULL() -> c_int {
    get_constants().mpi_proc_null
}

pub fn RSMPI_ROOT() -> c_int {
    get_constants().mpi_root
}

pub fn RSMPI_CART() -> c_int {
    get_constants().mpi_cart
}

pub fn RSMPI_DIST_GRAPH() -> c_int {
    get_constants().mpi_dist_graph
}

pub fn RSMPI_GRAPH() -> c_int {
    get_constants().mpi_graph
}

pub fn RSMPI_CONGRUENT() -> c_int {
    get_constants().mpi_congruent
}

pub fn RSMPI_IDENT() -> c_int {
    get_constants().mpi_ident
}

pub fn RSMPI_SIMILAR() -> c_int {
    get_constants().mpi_similar
}

pub fn RSMPI_UNEQUAL() -> c_int {
    get_constants().mpi_unequal
}

pub fn RSMPI_BSEND_OVERHEAD() -> c_int {
    get_constants().mpi_bsend_overhead
}

pub fn RSMPI_KEYVAL_INVALID() -> c_int {
    get_constants().mpi_keyval_invalid
}

pub fn RSMPI_UNDEFINED() -> c_int {
    get_constants().mpi_undefined
}

pub fn RSMPI_APPNUM() -> c_int {
    get_constants().mpi_appnum
}

pub fn RSMPI_HOST() -> c_int {
    get_constants().mpi_host
}

pub fn RSMPI_IO() -> c_int {
    get_constants().mpi_io
}

pub fn RSMPI_LASTUSEDCODE() -> c_int {
    get_constants().mpi_lastusedcode
}

pub fn RSMPI_TAG_UB() -> c_int {
    get_constants().mpi_tag_ub
}

pub fn RSMPI_UNIVERSE_SIZE() -> c_int {
    get_constants().mpi_universe_size
}

pub fn RSMPI_WIN_BASE() -> c_int {
    get_constants().mpi_win_base
}

pub fn RSMPI_WIN_CREATE_FLAVOR() -> c_int {
    get_constants().mpi_win_create_flavor
}

pub fn RSMPI_WIN_DISP_UNIT() -> c_int {
    get_constants().mpi_win_disp_unit
}

pub fn RSMPI_WIN_MODEL() -> c_int {
    get_constants().mpi_win_model
}

pub fn RSMPI_WIN_SIZE() -> c_int {
    get_constants().mpi_win_size
}

pub fn RSMPI_WTIME_IS_GLOBAL() -> c_int {
    get_constants().mpi_wtime_is_global
}

pub fn RSMPI_COMBINER_CONTIGUOUS() -> c_int {
    get_constants().mpi_combiner_contiguous
}

pub fn RSMPI_COMBINER_DARRAY() -> c_int {
    get_constants().mpi_combiner_darray
}

pub fn RSMPI_COMBINER_DUP() -> c_int {
    get_constants().mpi_combiner_dup
}

pub fn RSMPI_COMBINER_F90_COMPLEX() -> c_int {
    get_constants().mpi_combiner_f90_complex
}

pub fn RSMPI_COMBINER_F90_INTEGER() -> c_int {
    get_constants().mpi_combiner_f90_integer
}

pub fn RSMPI_COMBINER_F90_REAL() -> c_int {
    get_constants().mpi_combiner_f90_real
}

pub fn RSMPI_COMBINER_HINDEXED() -> c_int {
    get_constants().mpi_combiner_hindexed
}

pub fn RSMPI_COMBINER_HINDEXED_BLOCK() -> c_int {
    get_constants().mpi_combiner_hindexed_block
}

pub fn RSMPI_COMBINER_HVECTOR() -> c_int {
    get_constants().mpi_combiner_hvector
}

pub fn RSMPI_COMBINER_INDEXED() -> c_int {
    get_constants().mpi_combiner_indexed
}

pub fn RSMPI_COMBINER_INDEXED_BLOCK() -> c_int {
    get_constants().mpi_combiner_indexed_block
}

pub fn RSMPI_COMBINER_NAMED() -> c_int {
    get_constants().mpi_combiner_named
}

pub fn RSMPI_COMBINER_RESIZED() -> c_int {
    get_constants().mpi_combiner_resized
}

pub fn RSMPI_COMBINER_STRUCT() -> c_int {
    get_constants().mpi_combiner_struct
}

pub fn RSMPI_COMBINER_SUBARRAY() -> c_int {
    get_constants().mpi_combiner_subarray
}

pub fn RSMPI_COMBINER_VECTOR() -> c_int {
    get_constants().mpi_combiner_vector
}

pub fn RSMPI_COMM_TYPE_SHARED() -> c_int {
    get_constants().mpi_comm_type_shared
}

pub fn RSMPI_DISTRIBUTE_BLOCK() -> c_int {
    get_constants().mpi_distribute_block
}

pub fn RSMPI_DISTRIBUTE_CYCLIC() -> c_int {
    get_constants().mpi_distribute_cyclic
}

pub fn RSMPI_DISTRIBUTE_DFLT_DARG() -> c_int {
    get_constants().mpi_distribute_dflt_darg
}

pub fn RSMPI_DISTRIBUTE_NONE() -> c_int {
    get_constants().mpi_distribute_none
}

pub fn RSMPI_ERR_ACCESS() -> c_int {
    get_constants().mpi_err_access
}

pub fn RSMPI_ERR_AMODE() -> c_int {
    get_constants().mpi_err_amode
}

pub fn RSMPI_ERR_ARG() -> c_int {
    get_constants().mpi_err_arg
}

pub fn RSMPI_ERR_ASSERT() -> c_int {
    get_constants().mpi_err_assert
}

pub fn RSMPI_ERR_BAD_FILE() -> c_int {
    get_constants().mpi_err_bad_file
}

pub fn RSMPI_ERR_BASE() -> c_int {
    get_constants().mpi_err_base
}

pub fn RSMPI_ERR_BUFFER() -> c_int {
    get_constants().mpi_err_buffer
}

pub fn RSMPI_ERR_COMM() -> c_int {
    get_constants().mpi_err_comm
}

pub fn RSMPI_ERR_CONVERSION() -> c_int {
    get_constants().mpi_err_conversion
}

pub fn RSMPI_ERR_COUNT() -> c_int {
    get_constants().mpi_err_count
}

pub fn RSMPI_ERR_DIMS() -> c_int {
    get_constants().mpi_err_dims
}

pub fn RSMPI_ERR_DISP() -> c_int {
    get_constants().mpi_err_disp
}

pub fn RSMPI_ERR_DUP_DATAREP() -> c_int {
    get_constants().mpi_err_dup_datarep
}

pub fn RSMPI_ERR_FILE() -> c_int {
    get_constants().mpi_err_file
}

pub fn RSMPI_ERR_FILE_EXISTS() -> c_int {
    get_constants().mpi_err_file_exists
}

pub fn RSMPI_ERR_FILE_IN_USE() -> c_int {
    get_constants().mpi_err_file_in_use
}

pub fn RSMPI_ERR_GROUP() -> c_int {
    get_constants().mpi_err_group
}

pub fn RSMPI_ERR_INFO() -> c_int {
    get_constants().mpi_err_info
}

pub fn RSMPI_ERR_INFO_KEY() -> c_int {
    get_constants().mpi_err_info_key
}

pub fn RSMPI_ERR_INFO_NOKEY() -> c_int {
    get_constants().mpi_err_info_nokey
}

pub fn RSMPI_ERR_INFO_VALUE() -> c_int {
    get_constants().mpi_err_info_value
}

pub fn RSMPI_ERR_INTERN() -> c_int {
    get_constants().mpi_err_intern
}

pub fn RSMPI_ERR_IN_STATUS() -> c_int {
    get_constants().mpi_err_in_status
}

pub fn RSMPI_ERR_IO() -> c_int {
    get_constants().mpi_err_io
}

pub fn RSMPI_ERR_KEYVAL() -> c_int {
    get_constants().mpi_err_keyval
}

pub fn RSMPI_ERR_LASTCODE() -> c_int {
    get_constants().mpi_err_lastcode
}

pub fn RSMPI_ERR_LOCKTYPE() -> c_int {
    get_constants().mpi_err_locktype
}

pub fn RSMPI_ERR_NAME() -> c_int {
    get_constants().mpi_err_name
}

pub fn RSMPI_ERR_NOT_SAME() -> c_int {
    get_constants().mpi_err_not_same
}

pub fn RSMPI_ERR_NO_MEM() -> c_int {
    get_constants().mpi_err_no_mem
}

pub fn RSMPI_ERR_NO_SPACE() -> c_int {
    get_constants().mpi_err_no_space
}

pub fn RSMPI_ERR_NO_SUCH_FILE() -> c_int {
    get_constants().mpi_err_no_such_file
}

pub fn RSMPI_ERR_OP() -> c_int {
    get_constants().mpi_err_op
}

pub fn RSMPI_ERR_OTHER() -> c_int {
    get_constants().mpi_err_other
}

pub fn RSMPI_ERR_PENDING() -> c_int {
    get_constants().mpi_err_pending
}

pub fn RSMPI_ERR_PORT() -> c_int {
    get_constants().mpi_err_port
}

pub fn RSMPI_ERR_QUOTA() -> c_int {
    get_constants().mpi_err_quota
}

pub fn RSMPI_ERR_RANK() -> c_int {
    get_constants().mpi_err_rank
}

pub fn RSMPI_ERR_READ_ONLY() -> c_int {
    get_constants().mpi_err_read_only
}

pub fn RSMPI_ERR_REQUEST() -> c_int {
    get_constants().mpi_err_request
}

pub fn RSMPI_ERR_RMA_ATTACH() -> c_int {
    get_constants().mpi_err_rma_attach
}

pub fn RSMPI_ERR_RMA_CONFLICT() -> c_int {
    get_constants().mpi_err_rma_conflict
}

pub fn RSMPI_ERR_RMA_FLAVOR() -> c_int {
    get_constants().mpi_err_rma_flavor
}

pub fn RSMPI_ERR_RMA_RANGE() -> c_int {
    get_constants().mpi_err_rma_range
}

pub fn RSMPI_ERR_RMA_SHARED() -> c_int {
    get_constants().mpi_err_rma_shared
}

pub fn RSMPI_ERR_RMA_SYNC() -> c_int {
    get_constants().mpi_err_rma_sync
}

pub fn RSMPI_ERR_ROOT() -> c_int {
    get_constants().mpi_err_root
}

pub fn RSMPI_ERR_SERVICE() -> c_int {
    get_constants().mpi_err_service
}

pub fn RSMPI_ERR_SIZE() -> c_int {
    get_constants().mpi_err_size
}

pub fn RSMPI_ERR_SPAWN() -> c_int {
    get_constants().mpi_err_spawn
}

pub fn RSMPI_ERR_TAG() -> c_int {
    get_constants().mpi_err_tag
}

pub fn RSMPI_ERR_TOPOLOGY() -> c_int {
    get_constants().mpi_err_topology
}

pub fn RSMPI_ERR_TRUNCATE() -> c_int {
    get_constants().mpi_err_truncate
}

pub fn RSMPI_ERR_TYPE() -> c_int {
    get_constants().mpi_err_type
}

pub fn RSMPI_ERR_UNKNOWN() -> c_int {
    get_constants().mpi_err_unknown
}

pub fn RSMPI_ERR_UNSUPPORTED_DATAREP() -> c_int {
    get_constants().mpi_err_unsupported_datarep
}

pub fn RSMPI_ERR_UNSUPPORTED_OPERATION() -> c_int {
    get_constants().mpi_err_unsupported_operation
}

pub fn RSMPI_ERR_WIN() -> c_int {
    get_constants().mpi_err_win
}

pub fn RSMPI_SUCCESS() -> c_int {
    get_constants().mpi_success
}

pub fn RSMPI_LOCK_EXCLUSIVE() -> c_int {
    get_constants().mpi_lock_exclusive
}

pub fn RSMPI_LOCK_SHARED() -> c_int {
    get_constants().mpi_lock_shared
}

pub fn RSMPI_MODE_APPEND() -> c_int {
    get_constants().mpi_mode_append
}

pub fn RSMPI_MODE_CREATE() -> c_int {
    get_constants().mpi_mode_create
}

pub fn RSMPI_MODE_DELETE_ON_CLOSE() -> c_int {
    get_constants().mpi_mode_delete_on_close
}

pub fn RSMPI_MODE_EXCL() -> c_int {
    get_constants().mpi_mode_excl
}

pub fn RSMPI_MODE_NOCHECK() -> c_int {
    get_constants().mpi_mode_nocheck
}

pub fn RSMPI_MODE_NOPRECEDE() -> c_int {
    get_constants().mpi_mode_noprecede
}

pub fn RSMPI_MODE_NOPUT() -> c_int {
    get_constants().mpi_mode_noput
}

pub fn RSMPI_MODE_NOSTORE() -> c_int {
    get_constants().mpi_mode_nostore
}

pub fn RSMPI_MODE_NOSUCCEED() -> c_int {
    get_constants().mpi_mode_nosucceed
}

pub fn RSMPI_MODE_RDONLY() -> c_int {
    get_constants().mpi_mode_rdonly
}

pub fn RSMPI_MODE_RDWR() -> c_int {
    get_constants().mpi_mode_rdwr
}

pub fn RSMPI_MODE_SEQUENTIAL() -> c_int {
    get_constants().mpi_mode_sequential
}

pub fn RSMPI_MODE_UNIQUE_OPEN() -> c_int {
    get_constants().mpi_mode_unique_open
}

pub fn RSMPI_MODE_WRONLY() -> c_int {
    get_constants().mpi_mode_wronly
}

pub fn RSMPI_ORDER_C() -> c_int {
    get_constants().mpi_order_c
}

pub fn RSMPI_ORDER_FORTRAN() -> c_int {
    get_constants().mpi_order_fortran
}

pub fn RSMPI_SEEK_CUR() -> c_int {
    get_constants().mpi_seek_cur
}

pub fn RSMPI_SEEK_END() -> c_int {
    get_constants().mpi_seek_end
}

pub fn RSMPI_SEEK_SET() -> c_int {
    get_constants().mpi_seek_set
}

pub fn RSMPI_THREAD_FUNNELED() -> c_int {
    get_constants().mpi_thread_funneled
}

pub fn RSMPI_THREAD_MULTIPLE() -> c_int {
    get_constants().mpi_thread_multiple
}

pub fn RSMPI_THREAD_SERIALIZED() -> c_int {
    get_constants().mpi_thread_serialized
}

pub fn RSMPI_THREAD_SINGLE() -> c_int {
    get_constants().mpi_thread_single
}

pub fn RSMPI_TYPECLASS_COMPLEX() -> c_int {
    get_constants().mpi_typeclass_complex
}

pub fn RSMPI_TYPECLASS_INTEGER() -> c_int {
    get_constants().mpi_typeclass_integer
}

pub fn RSMPI_TYPECLASS_REAL() -> c_int {
    get_constants().mpi_typeclass_real
}

pub fn RSMPI_WIN_FLAVOR_ALLOCATE() -> c_int {
    get_constants().mpi_win_flavor_allocate
}

pub fn RSMPI_WIN_FLAVOR_CREATE() -> c_int {
    get_constants().mpi_win_flavor_create
}

pub fn RSMPI_WIN_FLAVOR_DYNAMIC() -> c_int {
    get_constants().mpi_win_flavor_dynamic
}

pub fn RSMPI_WIN_FLAVOR_SHARED() -> c_int {
    get_constants().mpi_win_flavor_shared
}

pub fn RSMPI_WIN_SEPARATE() -> c_int {
    get_constants().mpi_win_separate
}

pub fn RSMPI_WIN_UNIFIED() -> c_int {
    get_constants().mpi_win_unified
}

pub fn RSMPI_ARGV_NULL() -> *mut *mut c_char {
    get_constants().mpi_argv_null
}

pub fn RSMPI_ARGVS_NULL() -> *mut *mut *mut c_char {
    get_constants().mpi_argvs_null
}

pub fn RSMPI_ERRCODES_IGNORE() -> *mut c_int {
    get_constants().mpi_errcodes_ignore
}

pub fn RSMPI_UNWEIGHTED() -> *mut c_int {
    get_constants().mpi_unweighted
}

pub fn RSMPI_WEIGHTS_EMPTY() -> *mut c_int {
    get_constants().mpi_weights_empty
}

pub fn RSMPI_BOTTOM() -> *mut c_void {
    get_constants().mpi_bottom
}

pub fn RSMPI_IN_PLACE() -> *mut c_void {
    get_constants().mpi_in_place
}

pub fn RSMPI_COMM_NULL() -> MPI_Comm {
    get_constants().mpi_comm_null
}

pub fn RSMPI_COMM_SELF() -> MPI_Comm {
    get_constants().mpi_comm_self
}

pub fn RSMPI_COMM_WORLD() -> MPI_Comm {
    get_constants().mpi_comm_world
}

pub fn RSMPI_COMM_DUP_FN() -> MPI_Comm_copy_attr_function {
    get_constants().mpi_comm_dup_fn
}

pub fn RSMPI_COMM_NULL_COPY_FN() -> MPI_Comm_copy_attr_function {
    get_constants().mpi_comm_null_copy_fn
}

pub fn RSMPI_COMM_NULL_DELETE_FN() -> MPI_Comm_delete_attr_function {
    get_constants().mpi_comm_null_delete_fn
}

pub fn RSMPI_DUP_FN() -> MPI_Copy_function {
    get_constants().mpi_dup_fn
}

pub fn RSMPI_NULL_COPY_FN() -> MPI_Copy_function {
    get_constants().mpi_null_copy_fn
}

pub fn RSMPI_CONVERSION_FN_NULL() -> MPI_Datarep_conversion_function {
    get_constants().mpi_conversion_fn_null
}

pub fn RSMPI_2DOUBLE_PRECISION() -> MPI_Datatype {
    get_constants().mpi_2double_precision
}

pub fn RSMPI_2INT() -> MPI_Datatype {
    get_constants().mpi_2int
}

pub fn RSMPI_2INTEGER() -> MPI_Datatype {
    get_constants().mpi_2integer
}

pub fn RSMPI_2REAL() -> MPI_Datatype {
    get_constants().mpi_2real
}

pub fn RSMPI_AINT() -> MPI_Datatype {
    get_constants().mpi_aint
}

pub fn RSMPI_BYTE() -> MPI_Datatype {
    get_constants().mpi_byte
}

pub fn RSMPI_CHAR() -> MPI_Datatype {
    get_constants().mpi_char
}

pub fn RSMPI_CHARACTER() -> MPI_Datatype {
    get_constants().mpi_character
}

pub fn RSMPI_COMPLEX() -> MPI_Datatype {
    get_constants().mpi_complex
}

pub fn RSMPI_COMPLEX16() -> MPI_Datatype {
    get_constants().mpi_complex16
}

pub fn RSMPI_COMPLEX32() -> MPI_Datatype {
    get_constants().mpi_complex32
}

pub fn RSMPI_COMPLEX8() -> MPI_Datatype {
    get_constants().mpi_complex8
}

pub fn RSMPI_COUNT() -> MPI_Datatype {
    get_constants().mpi_count
}

pub fn RSMPI_CXX_BOOL() -> MPI_Datatype {
    get_constants().mpi_cxx_bool
}

pub fn RSMPI_CXX_DOUBLE_COMPLEX() -> MPI_Datatype {
    get_constants().mpi_cxx_double_complex
}

pub fn RSMPI_CXX_FLOAT_COMPLEX() -> MPI_Datatype {
    get_constants().mpi_cxx_float_complex
}

pub fn RSMPI_CXX_LONG_DOUBLE_COMPLEX() -> MPI_Datatype {
    get_constants().mpi_cxx_long_double_complex
}

pub fn RSMPI_C_BOOL() -> MPI_Datatype {
    get_constants().mpi_c_bool
}

pub fn RSMPI_C_COMPLEX() -> MPI_Datatype {
    get_constants().mpi_c_complex
}

pub fn RSMPI_C_DOUBLE_COMPLEX() -> MPI_Datatype {
    get_constants().mpi_c_double_complex
}

pub fn RSMPI_C_FLOAT_COMPLEX() -> MPI_Datatype {
    get_constants().mpi_c_float_complex
}

pub fn RSMPI_C_LONG_DOUBLE_COMPLEX() -> MPI_Datatype {
    get_constants().mpi_c_long_double_complex
}

pub fn RSMPI_DATATYPE_NULL() -> MPI_Datatype {
    get_constants().mpi_datatype_null
}

pub fn RSMPI_DOUBLE() -> MPI_Datatype {
    get_constants().mpi_double
}

pub fn RSMPI_DOUBLE_COMPLEX() -> MPI_Datatype {
    get_constants().mpi_double_complex
}

pub fn RSMPI_DOUBLE_INT() -> MPI_Datatype {
    get_constants().mpi_double_int
}

pub fn RSMPI_DOUBLE_PRECISION() -> MPI_Datatype {
    get_constants().mpi_double_precision
}

pub fn RSMPI_FLOAT() -> MPI_Datatype {
    get_constants().mpi_float
}

pub fn RSMPI_FLOAT_INT() -> MPI_Datatype {
    get_constants().mpi_float_int
}

pub fn RSMPI_INT() -> MPI_Datatype {
    get_constants().mpi_int
}

pub fn RSMPI_INT16_T() -> MPI_Datatype {
    get_constants().mpi_int16_t
}

pub fn RSMPI_INT32_T() -> MPI_Datatype {
    get_constants().mpi_int32_t
}

pub fn RSMPI_INT64_T() -> MPI_Datatype {
    get_constants().mpi_int64_t
}

pub fn RSMPI_INT8_T() -> MPI_Datatype {
    get_constants().mpi_int8_t
}

pub fn RSMPI_INTEGER() -> MPI_Datatype {
    get_constants().mpi_integer
}

pub fn RSMPI_INTEGER1() -> MPI_Datatype {
    get_constants().mpi_integer1
}

pub fn RSMPI_INTEGER2() -> MPI_Datatype {
    get_constants().mpi_integer2
}

pub fn RSMPI_INTEGER4() -> MPI_Datatype {
    get_constants().mpi_integer4
}

pub fn RSMPI_INTEGER8() -> MPI_Datatype {
    get_constants().mpi_integer8
}

pub fn RSMPI_LOGICAL() -> MPI_Datatype {
    get_constants().mpi_logical
}

pub fn RSMPI_LONG() -> MPI_Datatype {
    get_constants().mpi_long
}

pub fn RSMPI_LONG_DOUBLE() -> MPI_Datatype {
    get_constants().mpi_long_double
}

pub fn RSMPI_LONG_DOUBLE_INT() -> MPI_Datatype {
    get_constants().mpi_long_double_int
}

pub fn RSMPI_LONG_INT() -> MPI_Datatype {
    get_constants().mpi_long_int
}

pub fn RSMPI_LONG_LONG() -> MPI_Datatype {
    get_constants().mpi_long_long
}

pub fn RSMPI_LONG_LONG_INT() -> MPI_Datatype {
    get_constants().mpi_long_long_int
}

pub fn RSMPI_OFFSET() -> MPI_Datatype {
    get_constants().mpi_offset
}

pub fn RSMPI_PACKED() -> MPI_Datatype {
    get_constants().mpi_packed
}

pub fn RSMPI_REAL() -> MPI_Datatype {
    get_constants().mpi_real
}

pub fn RSMPI_REAL16() -> MPI_Datatype {
    get_constants().mpi_real16
}

pub fn RSMPI_REAL4() -> MPI_Datatype {
    get_constants().mpi_real4
}

pub fn RSMPI_REAL8() -> MPI_Datatype {
    get_constants().mpi_real8
}

pub fn RSMPI_SHORT() -> MPI_Datatype {
    get_constants().mpi_short
}

pub fn RSMPI_SHORT_INT() -> MPI_Datatype {
    get_constants().mpi_short_int
}

pub fn RSMPI_SIGNED_CHAR() -> MPI_Datatype {
    get_constants().mpi_signed_char
}

pub fn RSMPI_UINT16_T() -> MPI_Datatype {
    get_constants().mpi_uint16_t
}

pub fn RSMPI_UINT32_T() -> MPI_Datatype {
    get_constants().mpi_uint32_t
}

pub fn RSMPI_UINT64_T() -> MPI_Datatype {
    get_constants().mpi_uint64_t
}

pub fn RSMPI_UINT8_T() -> MPI_Datatype {
    get_constants().mpi_uint8_t
}

pub fn RSMPI_UNSIGNED() -> MPI_Datatype {
    get_constants().mpi_unsigned
}

pub fn RSMPI_UNSIGNED_CHAR() -> MPI_Datatype {
    get_constants().mpi_unsigned_char
}

pub fn RSMPI_UNSIGNED_LONG() -> MPI_Datatype {
    get_constants().mpi_unsigned_long
}

pub fn RSMPI_UNSIGNED_LONG_LONG() -> MPI_Datatype {
    get_constants().mpi_unsigned_long_long
}

pub fn RSMPI_UNSIGNED_SHORT() -> MPI_Datatype {
    get_constants().mpi_unsigned_short
}

pub fn RSMPI_WCHAR() -> MPI_Datatype {
    get_constants().mpi_wchar
}

pub fn RSMPI_NULL_DELETE_FN() -> MPI_Delete_function {
    get_constants().mpi_null_delete_fn
}

pub fn RSMPI_ERRHANDLER_NULL() -> MPI_Errhandler {
    get_constants().mpi_errhandler_null
}

pub fn RSMPI_ERRORS_ARE_FATAL() -> MPI_Errhandler {
    get_constants().mpi_errors_are_fatal
}

pub fn RSMPI_ERRORS_RETURN() -> MPI_Errhandler {
    get_constants().mpi_errors_return
}

pub fn RSMPI_FILE_NULL() -> MPI_File {
    get_constants().mpi_file_null
}

pub fn RSMPI_F_STATUS_IGNORE() -> *mut MPI_Fint {
    get_constants().mpi_f_status_ignore
}

pub fn RSMPI_F_STATUSES_IGNORE() -> *mut MPI_Fint {
    get_constants().mpi_f_statuses_ignore
}

pub fn RSMPI_GROUP_EMPTY() -> MPI_Group {
    get_constants().mpi_group_empty
}

pub fn RSMPI_GROUP_NULL() -> MPI_Group {
    get_constants().mpi_group_null
}

pub fn RSMPI_INFO_ENV() -> MPI_Info {
    get_constants().mpi_info_env
}

pub fn RSMPI_INFO_NULL() -> MPI_Info {
    get_constants().mpi_info_null
}

pub fn RSMPI_MESSAGE_NO_PROC() -> MPI_Message {
    get_constants().mpi_message_no_proc
}

pub fn RSMPI_MESSAGE_NULL() -> MPI_Message {
    get_constants().mpi_message_null
}

pub fn RSMPI_DISPLACEMENT_CURRENT() -> MPI_Offset {
    get_constants().mpi_displacement_current
}

pub fn RSMPI_BAND() -> MPI_Op {
    get_constants().mpi_band
}

pub fn RSMPI_BOR() -> MPI_Op {
    get_constants().mpi_bor
}

pub fn RSMPI_BXOR() -> MPI_Op {
    get_constants().mpi_bxor
}

pub fn RSMPI_LAND() -> MPI_Op {
    get_constants().mpi_land
}

pub fn RSMPI_LOR() -> MPI_Op {
    get_constants().mpi_lor
}

pub fn RSMPI_LXOR() -> MPI_Op {
    get_constants().mpi_lxor
}

pub fn RSMPI_MAX() -> MPI_Op {
    get_constants().mpi_max
}

pub fn RSMPI_MAXLOC() -> MPI_Op {
    get_constants().mpi_maxloc
}

pub fn RSMPI_MIN() -> MPI_Op {
    get_constants().mpi_min
}

pub fn RSMPI_MINLOC() -> MPI_Op {
    get_constants().mpi_minloc
}

pub fn RSMPI_NO_OP() -> MPI_Op {
    get_constants().mpi_no_op
}

pub fn RSMPI_OP_NULL() -> MPI_Op {
    get_constants().mpi_op_null
}

pub fn RSMPI_PROD() -> MPI_Op {
    get_constants().mpi_prod
}

pub fn RSMPI_REPLACE() -> MPI_Op {
    get_constants().mpi_replace
}

pub fn RSMPI_SUM() -> MPI_Op {
    get_constants().mpi_sum
}

pub fn RSMPI_REQUEST_NULL() -> MPI_Request {
    get_constants().mpi_request_null
}

pub fn RSMPI_STATUS_IGNORE() -> *mut MPI_Status {
    get_constants().mpi_status_ignore
}

pub fn RSMPI_STATUSES_IGNORE() -> *mut MPI_Status {
    get_constants().mpi_statuses_ignore
}

pub fn RSMPI_TYPE_DUP_FN() -> MPI_Type_copy_attr_function {
    get_constants().mpi_type_dup_fn
}

pub fn RSMPI_TYPE_NULL_COPY_FN() -> MPI_Type_copy_attr_function {
    get_constants().mpi_type_null_copy_fn
}

pub fn RSMPI_TYPE_NULL_DELETE_FN() -> MPI_Type_delete_attr_function {
    get_constants().mpi_type_null_delete_fn
}

pub fn RSMPI_WIN_NULL() -> MPI_Win {
    get_constants().mpi_win_null
}

pub fn RSMPI_WIN_DUP_FN() -> MPI_Win_copy_attr_function {
    get_constants().mpi_win_dup_fn
}

pub fn RSMPI_WIN_NULL_COPY_FN() -> MPI_Win_copy_attr_function {
    get_constants().mpi_win_null_copy_fn
}

pub fn RSMPI_WIN_NULL_DELETE_FN() -> MPI_Win_delete_attr_function {
    get_constants().mpi_win_null_delete_fn
}

// Additional constants used by rsmpi (loaded from MPIABI symbols)
pub fn RSMPI_MAX_LIBRARY_VERSION_STRING_fn() -> c_int {
    // MPI standard defines this as MPI_MAX_LIBRARY_VERSION_STRING
    // MPItrampoline exposes it as MPIABI_MAX_LIBRARY_VERSION_STRING
    static VAL: OnceLock<c_int> = OnceLock::new();
    *VAL.get_or_init(|| {
        let lib = loader::library();
        unsafe { *lib.get::<c_int>(b"MPIABI_MAX_LIBRARY_VERSION_STRING\0").expect("MPIABI_MAX_LIBRARY_VERSION_STRING") }
    })
}

pub fn RSMPI_MAX_LIBRARY_VERSION_STRING() -> c_int {
    RSMPI_MAX_LIBRARY_VERSION_STRING_fn()
}

pub fn RSMPI_MAX_PROCESSOR_NAME_fn() -> c_int {
    static VAL: OnceLock<c_int> = OnceLock::new();
    *VAL.get_or_init(|| {
        let lib = loader::library();
        unsafe { *lib.get::<c_int>(b"MPIABI_MAX_PROCESSOR_NAME\0").expect("MPIABI_MAX_PROCESSOR_NAME") }
    })
}

pub fn RSMPI_MAX_PROCESSOR_NAME() -> c_int {
    RSMPI_MAX_PROCESSOR_NAME_fn()
}

pub unsafe fn RSMPI_Wtime() -> c_double {
    crate::functions::MPI_Wtime()
}

pub unsafe fn RSMPI_Wtick() -> c_double {
    crate::functions::MPI_Wtick()
}
